
import { CV, Notification, Statistic, PopularItem, TrendItem } from './types';

export const MOCK_CVS: CV[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    profession: 'Frontend Developer',
    city: 'İstanbul',
    experienceYears: 5,
    language: 'İngilizce',
    languageLevel: 'İleri',
    photoUrl: 'https://picsum.photos/seed/ahmet/200/200',
    salaryMin: 45000,
    salaryMax: 60000,
    about: 'Deneyimli frontend developer, React ve Vue konusunda uzman. Modern web teknolojileri ve responsive tasarım konularında bilgili.',
    skills: ['React', 'TypeScript', 'Redux', 'Tailwind CSS', 'Next.js'],
    education: 'İstanbul Teknik Üniversitesi - Bilgisayar Mühendisliği',
    educationLevel: 'Lisans',
    graduationStatus: 'Mezun',
    workType: 'Remote',
    employmentType: 'Tam Zamanlı',
    militaryStatus: 'Yapıldı',
    maritalStatus: 'Evli',
    disabilityStatus: 'Yok',
    noticePeriod: '2 Hafta',
    travelStatus: 'Seyahat Engeli Yok',
    driverLicense: ['B'],
    isActive: true,
    views: 1250,
    isPlaced: false,
  },
  {
    id: '2',
    name: 'Selin Aras',
    profession: 'UI/UX Designer',
    city: 'Ankara',
    experienceYears: 3,
    language: 'Almanca',
    languageLevel: 'Orta',
    photoUrl: 'https://picsum.photos/seed/selin/200/200',
    salaryMin: 40000,
    salaryMax: 50000,
    about: 'Kullanıcı odaklı tasarımlar yapmayı seven, Figma ve Adobe XD araçlarına hakim tasarımcı.',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research'],
    education: 'ODTÜ - Endüstriyel Tasarım',
    educationLevel: 'Yüksek Lisans',
    graduationStatus: 'Mezun',
    workType: 'Hibrit',
    employmentType: 'Tam Zamanlı',
    militaryStatus: 'Muaf',
    maritalStatus: 'Bekar',
    disabilityStatus: 'Yok',
    isNew: true,
    views: 840,
    isPlaced: false,
  },
  {
    id: '3',
    name: 'Can Demir',
    profession: 'Backend Developer',
    city: 'İzmir',
    experienceYears: 8,
    language: 'İngilizce',
    languageLevel: 'İleri',
    photoUrl: 'https://picsum.photos/seed/can/200/200',
    salaryMin: 55000,
    salaryMax: 75000,
    about: 'Node.js ve Microservices mimarileri konusunda uzman backend mühendisi.',
    skills: ['Node.js', 'Go', 'Docker', 'Kubernetes', 'PostgreSQL'],
    education: 'Ege Üniversitesi - Yazılım Mühendisliği',
    views: 2100,
    isPlaced: true,
  },
];

export const WORK_TYPES = ['Remote', 'Hibrit', 'Ofis'];
export const EMPLOYMENT_TYPES = ['Tam Zamanlı', 'Yarı Zamanlı', 'Proje Bazlı', 'Freelance', 'Stajyer'];
export const EDUCATION_LEVELS = ['Lise', 'Önlisans', 'Lisans', 'Yüksek Lisans', 'Doktora'];
export const GRADUATION_STATUSES = ['Mezun', 'Öğrenci', 'Terk'];
export const MILITARY_STATUSES = ['Yapıldı', 'Muaf', 'Tecilli'];
export const MARITAL_STATUSES = ['Evli', 'Bekar'];
export const DISABILITY_STATUSES = ['Var', 'Yok'];
export const NOTICE_PERIODS = ['Hemen', '2 Hafta', '1 Ay', '2 Ay+'];
export const LANGUAGES = ['İngilizce', 'Almanca', 'Fransızca', 'Rusça', 'Arapça', 'İspanyolca'];
export const LANGUAGE_LEVELS = ['Başlangıç', 'Orta', 'İleri', 'Anadil'];
export const DRIVER_LICENSES = ['A1', 'A2', 'B', 'C', 'D', 'E'];
export const TRAVEL_STATUSES = ['Seyahat Engeli Yok', 'Seyahat Edemem'];

export const ALL_SKILLS = [
  'React', 'Vue', 'Angular', 'TypeScript', 'Node.js', 'Go', 'Python', 'Docker', 'Figma', 'Sketch',
  'UI/UX', 'SEO', 'Pazarlama', 'Satış', 'Finans', 'İnsan Karşılamaları', 'Proje Yönetimi', 'AWS', 'SQL'
];

export const POPULAR_PROFESSIONS: PopularItem[] = [
  { label: 'Aşçı', count: 45 },
  { label: 'Avukat', count: 32 },
  { label: 'Backend Developer', count: 156 },
  { label: 'Bankacı', count: 28 },
  { label: 'Bekçi', count: 12 },
  { label: 'Berber / Kuaför', count: 54 },
  { label: 'Bilgisayar Mühendisi', count: 88 },
  { label: 'Bulaşıkçı', count: 22 },
  { label: 'Büro Memuru', count: 41 },
  { label: 'Çağrı Merkezi Müşteri Temsilcisi', count: 134 },
  { label: 'Çırak', count: 18 },
  { label: 'Çocuk Gelişimi Uzmanı', count: 25 },
  { label: 'Data Analyst', count: 42 },
  { label: 'Depo Sorumlusu', count: 67 },
  { label: 'Dış Ticaret Uzmanı', count: 19 },
  { label: 'Diş Hekimi', count: 14 },
  { label: 'Diyetisyen', count: 11 },
  { label: 'Doktor', count: 28 },
  { label: 'E-Ticaret Uzmanı', count: 53 },
  { label: 'Eczacı', count: 9 },
  { label: 'Editör', count: 16 },
  { label: 'Eğitim Danışmanı', count: 22 },
  { label: 'Elektrik Teknikeri', count: 38 },
  { label: 'Elektrikçi', count: 47 },
  { label: 'Emlak Danışmanı', count: 31 },
  { label: 'Endüstri Mühendisi', count: 26 },
  { label: 'Fırıncı', count: 14 },
  { label: 'Finans Uzmanı', count: 98 },
  { label: 'Fizyoterapist', count: 15 },
  { label: 'Frontend Developer', count: 234 },
  { label: 'Fullstack Developer', count: 112 },
  { label: 'Garson', count: 145 },
  { label: 'Gazeteci', count: 8 },
  { label: 'Gıda Mühendisi', count: 14 },
  { label: 'Grafik Tasarımcı', count: 118 },
  { label: 'Gümrük Müşaviri', count: 7 },
  { label: 'Güvenlik Görevlisi', count: 82 },
  { label: 'Halkla İlişkiler Uzmanı', count: 24 },
  { label: 'Hemşire', count: 43 },
  { label: 'Hukuk Müşaviri', count: 12 },
  { label: 'İç Mimar', count: 21 },
  { label: 'İdari İşler Uzmanı', count: 35 },
  { label: 'İK Uzmanı', count: 156 },
  { label: 'İletişim Tasarımı', count: 13 },
  { label: 'İnşaat Mühendisi', count: 38 },
  { label: 'İş Analisti', count: 44 },
  { label: 'Kamyon Şoförü', count: 29 },
  { label: 'Kasiyer', count: 92 },
  { label: 'Kaynakçı', count: 21 },
  { label: 'Kıdemli Yazılım Uzmanı', count: 64 },
  { label: 'Klima Tamircisi', count: 15 },
  { label: 'Komi', count: 48 },
  { label: 'Kurye', count: 76 },
  { label: 'Lojistik Operasyon Uzmanı', count: 32 },
  { label: 'Mağaza Müdürü', count: 41 },
  { label: 'Makine Mühendisi', count: 33 },
  { label: 'Malikane Görevlisi', count: 4 },
  { label: 'Manav', count: 11 },
  { label: 'Marangoz', count: 19 },
  { label: 'Marketing Manager', count: 52 },
  { label: 'Medya Planlama Uzmanı', count: 14 },
  { label: 'Mimar', count: 37 },
  { label: 'Mobile Developer', count: 78 },
  { label: 'Mobilya Ustası', count: 22 },
  { label: 'Muhasebeci', count: 124 },
  { label: 'Müşteri İlişkileri Yöneticisi', count: 56 },
  { label: 'Mütercim Tercüman', count: 18 },
  { label: 'Operasyon Sorumlusu', count: 42 },
  { label: 'Öğretmen', count: 68 },
  { label: 'Özel Güvenlik', count: 55 },
  { label: 'Pazarlama Uzmanı', count: 112 },
  { label: 'Personel Özlük İşleri', count: 21 },
  { label: 'Peyzaj Mimarı', count: 11 },
  { label: 'Pilot', count: 5 },
  { label: 'Plasiyer', count: 24 },
  { label: 'Polis', count: 12 },
  { label: 'Proje Yöneticisi', count: 72 },
  { label: 'Psikolog', count: 29 },
  { label: 'Resepsiyonist', count: 34 },
  { label: 'Reklam Yazarı', count: 19 },
  { label: 'Saha Elemanı', count: 46 },
  { label: 'Satın Alma Uzmanı', count: 38 },
  { label: 'Satış Danışmanı', count: 189 },
  { label: 'Sekreter', count: 61 },
  { label: 'SEO Uzmanı', count: 27 },
  { label: 'Siber Güvenlik Uzmanı', count: 34 },
  { label: 'Sıhhi Tesisatçı', count: 31 },
  { label: 'Sigorta Satış Uzmanı', count: 22 },
  { label: 'Sistem Yöneticisi', count: 41 },
  { label: 'Sosyal Medya Uzmanı', count: 85 },
  { label: 'Şoför', count: 94 },
  { label: 'Taksi Şoförü', count: 18 },
  { label: 'Tasarımcı', count: 56 },
  { label: 'Tekniker', count: 48 },
  { label: 'Teknisyen', count: 51 },
  { label: 'Temizlik Görevlisi', count: 88 },
  { label: 'Tesisatçı', count: 27 },
  { label: 'Tıbbi Mümessil', count: 19 },
  { label: 'Turizm Rehberi', count: 14 },
  { label: 'UI/UX Designer', count: 96 },
  { label: 'Usta', count: 33 },
  { label: 'Üretim Elemanı', count: 114 },
  { label: 'Vale', count: 21 },
  { label: 'Veri Tabanı Yöneticisi', count: 24 },
  { label: 'Veteriner', count: 12 },
  { label: 'Web Tasarımcı', count: 62 },
  { label: 'Yazılım Geliştirici', count: 450 },
  { label: 'Yazılım Test Mühendisi', count: 48 },
  { label: 'Yönetici Asistanı', count: 52 },
  { label: 'Ziraat Mühendisi', count: 18 }
];

export const POPULAR_CITIES: PopularItem[] = [
  { label: "Adana", count: 42 },
  { label: "Adıyaman", count: 12 },
  { label: "Afyonkarahisar", count: 15 },
  { label: "Ağrı", count: 8 },
  { label: "Aksaray", count: 11 },
  { label: "Amasya", count: 9 },
  { label: "Ankara", count: 230 },
  { label: "Antalya", count: 76 },
  { label: "Ardahan", count: 4 },
  { label: "Artvin", count: 6 },
  { label: "Aydın", count: 22 },
  { label: "Balıkesir", count: 28 },
  { label: "Bartın", count: 7 },
  { label: "Batman", count: 14 },
  { label: "Bayburt", count: 3 },
  { label: "Bilecik", count: 8 },
  { label: "Bingöl", count: 6 },
  { label: "Bitlis", count: 7 },
  { label: "Bolu", count: 12 },
  { label: "Burdur", count: 9 },
  { label: "Bursa", count: 98 },
  { label: "Çanakkale", count: 18 },
  { label: "Çankırı", count: 5 },
  { label: "Çorum", count: 13 },
  { label: "Denizli", count: 31 },
  { label: "Diyarbakır", count: 35 },
  { label: "Düzce", count: 11 },
  { label: "Edirne", count: 16 },
  { label: "Elazığ", count: 19 },
  { label: "Erzincan", count: 9 },
  { label: "Erzurum", count: 22 },
  { label: "Eskişehir", count: 45 },
  { label: "Gaziantep", count: 58 },
  { label: "Giresun", count: 12 },
  { label: "Gümüşhane", count: 5 },
  { label: "Hakkari", count: 3 },
  { label: "Hatay", count: 29 },
  { label: "Iğdır", count: 6 },
  { label: "Isparta", count: 14 },
  { label: "İstanbul", count: 450 },
  { label: "İzmir", count: 180 },
  { label: "Kahramanmaraş", count: 25 },
  { label: "Karabük", count: 10 },
  { label: "Karaman", count: 8 },
  { label: "Kars", count: 7 },
  { label: "Kastamonu", count: 11 },
  { label: "Kayseri", count: 41 },
  { label: "Kilis", count: 5 },
  { label: "Kırıkkale", count: 12 },
  { label: "Kırklareli", count: 13 },
  { label: "Kırşehir", count: 9 },
  { label: "Kocaeli", count: 88 },
  { label: "Konya", count: 55 },
  { label: "Kütahya", count: 16 },
  { label: "Malatya", count: 24 },
  { label: "Manisa", count: 32 },
  { label: "Mardin", count: 15 },
  { label: "Mersin", count: 48 },
  { label: "Muğla", count: 34 },
  { label: "Muş", count: 7 },
  { label: "Nevşehir", count: 10 },
  { label: "Niğde", count: 9 },
  { label: "Ordu", count: 18 },
  { label: "Osmaniye", count: 12 },
  { label: "Rize", count: 11 },
  { label: "Sakarya", count: 42 },
  { label: "Samsun", count: 38 },
  { label: "Şanlıurfa", count: 28 },
  { label: "Siirt", count: 6 },
  { label: "Sinop", count: 7 },
  { label: "Sivas", count: 18 },
  { label: "Şırnak", count: 5 },
  { label: "Tekirdağ", count: 32 },
  { label: "Tokat", count: 13 },
  { label: "Trabzon", count: 29 },
  { label: "Tunceli", count: 4 },
  { label: "Uşak", count: 11 },
  { label: "Van", count: 16 },
  { label: "Yalova", count: 14 },
  { label: "Yozgat", count: 8 },
  { label: "Zonguldak", count: 15 }
];

export const EXPERIENCE_LEVELS: PopularItem[] = [
  { label: 'Stajyer / Yeni Mezun', count: 120 },
  { label: 'Junior (1-3 Yıl)', count: 340 },
  { label: 'Mid-Level (3-5 Yıl)', count: 210 },
  { label: 'Senior (5-10 Yıl)', count: 150 },
  { label: 'Expert (10+ Yıl)', count: 72 },
];

export const STATISTICS: Statistic[] = [
  { label: 'Toplam CV', value: '1,234' },
  { label: 'Aktif İş Arayan', value: '892' },
  { label: 'Bu Hafta Yeni', value: '+45' },
  { label: 'Toplam Görüntülenme', value: '12.4k' },
  { label: 'Kayıtlı Şirketler', value: '428' },
  { label: 'Başarılı Eşleşme', value: '156' },
];

export const TRENDS: TrendItem[] = [
  { label: 'Backend Developer', growth: 92 },
  { label: 'Satış Müdürü', growth: 84 },
  { label: 'Grafik Tasarımcı', growth: 76 },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'CONTACT_REQUEST',
    title: 'İletişim İsteği',
    message: 'ABC Teknoloji sizinle iletişime geçmek istiyor.',
    time: '2 saat önce',
    isRead: false,
    companyName: 'ABC Teknoloji',
  },
];
