import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translation dictionary for demo/infrastructure purposes
// In a real app, this would be imported from separate JSON files
const translations: Record<Language, Record<string, string>> = {
    tr: {
        'settings.general': 'Genel',
        'settings.language': 'Dil Seçimi',
        'settings.language_desc': 'Uygulamanın görüntüleme dilini değiştirin.',
        'settings.save': 'Kaydet',
        'settings.cancel': 'Vazgeç',
        'settings.account': 'Hesap',
        'settings.security': 'Güvenlik',
        'settings.notifications': 'Bildirimler',
        'nav.search_placeholder': 'Aradığın yeteneği, hayalindeki işi bul...',
        'nav.employer_profile': 'İş Veren Profili',
        'nav.create_cv': 'CV Oluştur',
        'nav.fix_cv': 'CV\'yi Düzelt',
        'nav.employer': 'İş Veren',
        'nav.job_seeker': 'İş Arayan',
        'sidebar.job_finders': 'Kartvizid\'te İş Bulanlar',
        'sidebar.popular_professions': 'Talep Gören Meslekler',
        'sidebar.featured_cities': 'Öne Çıkan Şehirler',
        'sidebar.platform_stats': 'Kartvizid İstatistikleri',
        'stats.total_cv': 'Toplam CV',
        'stats.active_seekers': 'Aktif İş Arayan',
        'stats.new_this_week': 'Bu Hafta Yeni',
        'stats.total_views': 'Toplam Görüntülenme',
        'stats.matches': 'Başarılı Eşleşme',
        'sidebar.no_job_finders': 'Henüz iş bulan yok.',
        'sidebar.employers': 'İş Verenler',
        'sidebar.most_viewed': 'En Çok Görüntülenen Kartvizidler',
        'sidebar.no_data': 'Henüz veri yok.',
        'sidebar.no_featured': 'Henüz öne çıkan yok.',
        'feed.list_title': 'Kartvizid Listesi',
        'feed.sort': 'SIRALAMA',
        'feed.no_results': 'Sonuç bulunamadı.',
        'feed.reset_filters': 'Filtreleri Sıfırla',
        'feed.prev': 'Önceki',
        'feed.next': 'Sonraki',
        'feed.page': 'Sayfa',
        'mobile.cancel': 'İptal',
        // Filters
        'filters.categories': 'Tüm Kategoriler',
        'filters.city': 'Şehir Seçin',
        'filters.experience': 'Deneyim Seviyesi',
        'filters.advanced': 'Gelişmiş Filtreler',
        'filters.reset': 'Sıfırla',
        'filters.show_more': 'Daha Fazla Göster',
        // Footer
        'footer.brand_desc': 'Türkiye\'nin yeni nesil dijital CV ve iş eşleşme platformu. Kariyer yolculuğunuzda size en uygun fırsatları sunmak için buradayız.',
        'footer.usage': 'Site Kullanımı',
        'footer.general_terms': 'Genel Koşullar',
        'footer.security': 'Güvenlik İpuçları',
        'footer.faq': 'Sıkça Sorulan Sorular',
        'footer.help': 'Yardım Merkezi',
        'footer.services': 'Hizmetlerimiz',
        'footer.data_policy': 'Veri Politikamız',
        'footer.kvkk': 'KVKK Aydınlatma',
        'footer.cookie_policy': 'Çerez Politikası',
        'footer.membership_agreement': 'Üyelik Sözleşmesi',
        'footer.data_owner_form': 'Veri Sahibi Başvuru Formu',
        'footer.mobile_app': 'Mobil Uygulama',
        'footer.mobile_desc': 'İş fırsatlarını cebinizden takip edin.',
        'footer.copyright': '© 2026 Kartvizid. Tüm hakları saklıdır.',
        // Business Card
        'card.view': 'GÖRÜNTÜLE',
        'card.years_exp': 'Yıl Deneyim',
        'card.email_visible': 'E-posta Görünür',
        'card.phone_visible': 'Telefon Görünür',
        // Forms
        'form.cv_create_title': 'Dijital Kartvizid\'ini yani Cv\'ni Oluştur',
        'form.cv_create_subtitle': 'İşverenlerin sizi keşfetmesi için tüm detayları doldurun',
        'form.basic_info': '1. TEMEL BİLGİLER',
        'form.basic_info_subtitle': 'Profilinizin dış dünyaya bakan yüzü',
        'form.work_pref': '2. İŞ TERCİHLERİ',
        'form.work_pref_subtitle': 'Hangi koşullarda çalışmak istiyorsunuz?',
        'form.exp_skills': '3. EĞİTİM & YETENEKLER',
        'form.exp_skills_subtitle': 'Akademik geçmiş ve uzmanlık alanlarınız',
        'form.personal': '4. KİŞİSEL DETAYLAR',
        'form.personal_subtitle': 'Özel durumlar ve yasal detaylar',
        'form.about': '5. KENDİNİZİ TANITIN',
        'form.about_subtitle': 'İşverenlerin sizi tanıması için son dokunuş',
        'form.references': 'REFERANSLAR',
        'form.references_subtitle': 'Sizi daha yakından tanımamız için referanslarınız',
        'form.required': 'Zorunlu',
        'form.optional': 'Opsiyonel',
        'form.save': 'Kaydet',
        'form.cancel': 'Vazgeç',
        // Form Fields
        'form.fullname': 'Ad Soyad',
        'form.profession': 'Meslek / Ünvan',
        'form.city': 'Şehir',
        'form.district': 'İlçe',
        'form.experience': 'Tecrübe (Yıl)',
        'form.work_status': 'Çalışma Durumu',
        'form.working': 'Çalışıyorum',
        'form.not_working': 'Çalışmıyorum',
        'form.job_seeking': 'İş Arıyorum',
        'form.contact_info': 'İletişim Bilgileri (Opsiyonel)',
        'form.email': 'E-posta Adresi',
        'form.phone': 'Telefon Numarası',
        'form.visible': 'Görünür',
        'form.hidden': 'Gizli',
        'form.work_model': 'Çalışma Modeli',
        'form.employment_type': 'Çalışma Şekli',
        'form.salary_exp': 'Maaş Beklentisi (Aylık Net)',
        'form.monthly_net': 'Aylık Net',
        'form.education_info': 'Eğitim Bilgileri',
        'form.languages': 'Yabancı Diller',
        'form.certificates': 'Sertifikalar & Kurslar',
        'form.skills': 'Uzmanlık Alanları',
        'form.military': 'Askerlik Durumu',
        'form.driving_license': 'Sürücü Belgesi',
        'form.marital': 'Medeni Durum',
        'form.travel': 'Seyahat Durumu',
        'form.disability': 'Engellilik Durumu',
        'form.start_date': 'İşe Başlama Süresi',
        'form.about_me': 'HAKKINDA',
        'form.add_new': 'Yeni Ekle',
        'form.add': 'Ekle',
        // Company Form
        'company.create_title': 'İş Veren Profilinizi Oluşturun',
        'company.create_subtitle': 'Adayların sizi tanıması için kurumsal bilgilerinizi girin',
        'company.identity': '1. KURUMSAL KİMLİK',
        'company.identity_subtitle': 'İş veren profilinizin görünen yüzü',
        'company.logo': 'Logo',
        'company.name': 'İş Veren / Kurum Adı',
        'company.industry': 'Sektör',
        'company.website': 'Web Sitesi',
        'company.about_section': '2. İŞ VEREN HAKKINDA',
        'company.about_subtitle': 'Kültürünüzü ve vizyonunuzu anlatın',
        'company.about_placeholder': 'Kendinizden ve şirketinizden bahsedin...',
        'company.about_hint': 'Bu bilgiler adayların şirketinizi tanıması için önemlidir.',
        'company.save': 'Profili Kaydet',
        'company.address': 'Adres Detayı',
        'company.country': 'Ülke',

        // New Form Keys
        'form.work_history': 'İŞ DENEYİMİ',
        'form.history_subtitle': 'Geçmişten günümüze kariyer yolculuğunuz',
        'form.add_experience': 'Yeni Deneyim Ekle',
        'form.currently_working': 'Şu an burada çalışıyorum',
        'form.institution': 'Kurum Adı',
        'form.position': 'Pozisyon',
        'form.start_date_label': 'Başlangıç',
        'form.end_date_label': 'Bitiş',
        'form.university': 'Üniversite / Okul',
        'form.department': 'Bölüm',
        'form.add_education': 'Eğitim Ekle',
        'form.add_language': 'Dil Ekle',
        'form.cert_name': 'Sertifika / Kurs Adı',
        'form.cert_issuer': 'Veren Kurum (Opsiyonel)',
        'form.cert_date': 'Alınan Tarih',
        'form.add_certificate': 'Sertifika Ekle',
        'form.add_reference': 'Yeni Referans Ekle',
        'form.add_list': 'Listeye Ekle',
        'form.save_publish': 'Kaydet ve Yayına Al',
        'form.kvkk_text': 'Verdiğim bilgilerin doğruluğunu teyit ediyorum. KVKK Aydınlatma Metni uyarınca kişisel verilerimin işlenmesini onaylıyorum.',
        'success.job_found_title': 'TEBRİKLER!',
        'success.job_found_msg': 'Yeni işinizde başarılar dileriz! Kartvizid ailesi olarak kariyer yolculuğunuzda yanınızda olmaktan mutluluk duyduk.',
        'success.close_btn': 'TEŞEKKÜRLER',
        'success.card_footer': 'KARTVİZİD TEBRİK KARTI',
        'form.no_skills': 'Henüz yetenek eklemediniz.',
        'form.about_placeholder': 'Deneyimlerinizden ve uzmanlığınızdan bahsederek kendinizi 1-2 cümleyle etkileyici bir şekilde tanıtın...',
        'form.fullname_example': 'Örn: Mehmet Can',
        'form.profession_example': 'Örn: Senior React Dev',



        // Profile View (CV & Company)
        'profile.cv_title': 'Dijital Kartvizid Profili',
        'profile.cv_subtitle': 'Adayın profesyonel ve kişisel tüm detayları',
        'profile.company_title': 'İş Veren Profili',
        'profile.company_subtitle': 'Kurumsal bilgiler ve detaylar',
        'profile.basic_info': '1. TEMEL BİLGİLER',
        'profile.work_pref': '2. İŞ TERCİHLERİ',
        'profile.work_exp': '3. İŞ DENEYİMİ',
        'profile.edu_skills': '4. EĞİTİM & YETENEKLER',
        'profile.personal': '5. KİŞİSEL DETAYLAR',
        'profile.about': '6. HAKKINDA',
        'profile.references': '7. REFERANSLAR',
        'profile.contact': '8. İLETİŞİM BİLGİLERİ',
        'profile.download_cv': 'CV\'mi İndir',
        'profile.share_cv': 'CV\'mi Paylaş',
        'profile.job_found': '🎉 İŞİMİ BULDUM',
        'profile.request_sent': 'İstek Gönderildi',
        'profile.cancel_request': 'İsteği İptal Et',
        'profile.contact_request': 'İletişime Geç',
        'profile.contact_open': 'İletişim Bilgileri Açık',
        'profile.warning_hidden': 'İletişime geç isteğiniz onaylanmadan kişisel bilgileri göremezsiniz.',
        'profile.approve_request': 'İsteği Onayla',
        'profile.reject_request': 'Reddet',
        'profile.hide_contact': '🚫 İLETİŞİM BİLGİLERİNİ GİZLE',
        'profile.approved_msg': '✅ İletişim isteği onaylandı.',
        'profile.rejected_msg': 'tarafından gönderilen iletişim isteğini reddettiniz.',
        'profile.undo_reject': 'İSTEĞİ ONAYLA',
        'profile.close': 'KAPAT',
        'profile.settings': 'Ayarlar',
        'profile.logout': 'Çıkış Yap',

        // Notifications
        'notif.title': 'Tüm Bildirimler',
        'notif.clear_all': 'BİLDİRİMLERİ TEMİZLE',
        'notif.empty': 'Henüz bildiriminiz yok',
        'notif.view_profile': 'Profili Gör',
        'notif.approved': 'Onaylandı',
        'notif.rejected': 'Reddedildi',
        'notif.pending': 'Bekliyor',
        'notif.sent_request': 'seninle iletişime geçmek istiyor. Firması:',
        'notif.req_approved': 'iletişim isteğinizi onayladı. Artık iletişim bilgilerini görebilirsiniz.',
        'notif.req_rejected': 'iletişim isteğinizi reddetti.',
        'notif.you_rejected': 'kişisinin iletişim isteğini reddettiniz.',

        // Common & Values
        'common.none': 'Yok',
        'common.no_problem': 'Sorun Yok',
        'common.immediately': 'Hemen',
        'common.done': 'Yapıldı',
        'common.ongoing': 'Devam Ediyor',
        'errors.no_about': 'Aday kendini tanıtacak bir yazı eklememiş.',
        'errors.no_exp': 'İş deneyimi eklenmemiş.',
        'errors.no_ref': 'Referans eklenmemiş.',
        'errors.no_contact': 'İletişim bilgisi girilmemiş.',

        // Mappings
        'emp.full_time': 'Tam Zamanlı',
        'emp.part_time': 'Yarı Zamanlı',
        'emp.project': 'Proje Bazlı',
        'work.office': 'Ofis',
        'work.remote': 'Uzaktan',
        'work.hybrid': 'Hibrit',
        'military.done': 'Yapıldı',
        'military.exempt': 'Muaf',
        'military.postponed': 'Tecilli',
        'military.not_obligated': 'Yükümlü Değil',
        'marital.single': 'Bekar',
        'marital.married': 'Evli',
        'grad.graduated': 'Mezun',
        'grad.student': 'Öğrenci',
        'lang.english': 'İngilizce',
        'lang.german': 'Almanca',
        'lang.french': 'Fransızca',
        'lang.spanish': 'İspanyolca',
        'lang.turkish': 'Türkçe',
        'lang.russian': 'Rusça',
        'lang.arabic': 'Arapça',
        'level.beginner': 'Başlangıç',
        'level.intermediate': 'Orta',
        'level.advanced': 'İleri',
        'level.native': 'Anadil',
        'travel.yes': 'Seyahat Edebilir',
        'travel.no': 'Seyahat Edemez',
        'travel.no_barrier': 'Seyahat Engeli Yok',
        'sort.default': 'Varsayılan',
        'sort.newest': 'En Yeniler',
        'sort.oldest': 'En Eskiler',
        'promo.premium_title': 'Premium Ayrıcalığı',
        'promo.premium_desc': 'Öne çıkın, fark edilin. Kariyerinizde hız limitlerini kaldırın.',
        'promo.employer_title': 'Nokta Atışı Yetenek',
        'promo.employer_desc': 'İlanla vakit kaybetmeyin. Aradığınız profesyoneli doğrudan bulun.',
        'promo.seeker_title': 'İş Seni Bulsun',
        'promo.seeker_desc': 'Sen arama, onlar seni keşfetsin. Profilin senin yerine çalışsın.',
        'promo.tips_title': 'Profesyonel İpuçları',
        'promo.tips_desc': 'Kusursuz bir ilk izlenim için uzman tavsiyelerini keşfet.',
        'account.title': 'Hesabım',
        'account.settings': 'Ayarlar',
        'account.appearance': 'Görünüm',
        'account.dark': 'Koyu',
        'account.light': 'Aydınlık',
        'account.sign_out': 'Çıkış Yap',
        'account.promo_text': 'DİJİTAL KARTVİZİD\'İNİ OLUŞTURUP İŞVERENLER TARAFINDAN KEŞFEDİLMEYE HEMEN BAŞLA!',
        'settings.header_title': 'Hesap Ayarları',
        'settings.header_subtitle': 'Profil ve güvenlik tercihlerinizi yönetin',
        'settings.account_summary': 'Hesap Özeti',
        'settings.email_label': 'E-posta',
        'settings.member_since': 'Üyelik Tarihi',
        'settings.user_id': 'Kullanıcı ID',
        'settings.delete_account': 'Hesabımı Sil',
        'settings.delete_desc_emp': 'İş veren profiliniz ve tüm verileriniz kalıcı olarak silinir.',
        'settings.delete_desc_seek': 'CV\'niz, başvurularınız ve profiliniz kalıcı olarak silinir.',
        'settings.delete_warning': 'Dikkat: Bu işlem geri alınamaz. Silme işleminden sonra tüm verilerinize erişimi kaybedeceksiniz.',
        'settings.delete_btn': 'Hesabı Sil',
        'settings.delete_confirm_title': 'Hesabınızı silmek istediğinize emin misiniz?',
        'settings.delete_confirm_desc_emp': 'Bu işlem geri alınamaz. İş veren profiliniz ve tüm verileriniz kalıcı olarak silinecektir.',
        'settings.delete_confirm_desc_seek': 'Bu işlem geri alınamaz. CV\'niz, profiliniz ve tüm verileriniz kalıcı olarak silinecektir.',
        'settings.delete_confirm_yes': 'Evet, Hesabımı Sil',
        'settings.change_email': 'E-posta Değiştir',
        'settings.new_email': 'Yeni e-posta adresi',
        'settings.update': 'Güncelle',
        'settings.change_password': 'Şifre Değiştir',
        'settings.new_password': 'Yeni şifre',
        'settings.new_password_confirm': 'Yeni şifre (tekrar)',
        'settings.update_password': 'Şifreyi Güncelle',
        'settings.notif_email_title': 'E-posta Bildirimleri',
        'settings.notif_email_desc': 'Önemli güncellemeler ve aktiviteler hakkında e-posta al.',
        'settings.notif_marketing_title': 'Pazarlama İletileri',
        'settings.notif_marketing_desc': 'Yeni özellikler ve kampanyalar hakkında bilgi ver.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Stajyer',
        'edu.high_school': 'Lise',
        'edu.associate': 'Önlisans',
        'edu.bachelor': 'Lisans',
        'edu.master': 'Yüksek Lisans',
        'edu.doctorate': 'Doktora',
        'grad.dropped_out': 'Terk',
        'notice.immediately': 'Hemen',
        'notice.2_weeks': '2 Hafta',
        'notice.1_month': '1 Ay',
        'notice.2_months_plus': '2 Ay+',
        'disability.yes': 'Var',
        'disability.no': 'Yok',

        'travel.cannot_travel': 'Seyahat Edemem',
        'filter.apply': 'Filtreleri Uygula',
        'filter.search_prof_placeholder': 'Pozisyon Ara (Örn: Yazılım, Garson...)',
        'filter.search_city_placeholder': 'Şehir Ara (Örn: İstanbul, Antalya...)',
        'filter.salary_title': 'MAAŞ BEKLENTİSİ (₺)',
        'filter.salary_min': 'En Az',
        'filter.salary_max': 'En Çok',
        'filter.search_placeholder_dropdown': 'Aramaya başlayın...',
        'filter.no_results_dropdown': 'Sonuç bulunamadı...',
        'filter.all_reset': 'Tümü (Sıfırla)',
        'filter.subtitle': 'Kriterlerinize en uygun sonuçları detaylı listeleyin',
        'filter.profession_label': 'POZİSYON / MESLEK',
        'filter.location_label': 'LOKASYON / ŞEHİR',
        'filter.work_model_label': 'Çalışma Modeli',
        'filter.emp_type_label': 'Çalışma Şekli',
        'filter.edu_level_label': 'Eğitim Seviyesi',
        'filter.grad_status_label': 'Mezuniyet Durumu',
        'filter.exp_level_label': 'Deneyim Seviyesi',
        'filter.lang_label': 'Yabancı Dil',
        'filter.lang_level_label': 'Dil Seviyesi',
        'filter.travel_status_label': 'Seyahat Durumu',
        'filter.marital_status_label': 'Medeni Durum',
        'filter.disability_status_label': 'Engellilik Durumu',
        'filter.driver_license_label': 'Sürücü Belgesi',
        'filter.military_status_label': 'Askerlik Durumu',
        'filter.skills_label': 'Önemli Yetenekler',
    },
    en: {
        'settings.general': 'General',
        'settings.language': 'Language Selection',
        'settings.language_desc': 'Change the display language of the application.',
        'settings.save': 'Save',
        'settings.cancel': 'Cancel',
        'settings.account': 'Account',
        'settings.security': 'Security',
        'settings.notifications': 'Notifications',
        'nav.search_placeholder': 'Search profession, name or city...',
        'nav.employer_profile': 'Employer Profile',
        'nav.create_cv': 'Create CV',
        'nav.fix_cv': 'Edit CV',
        'nav.employer': 'Employer',
        'nav.job_seeker': 'Job Seeker',
        'sidebar.job_finders': 'Hired on Kartvizid',
        'sidebar.popular_professions': 'Popular Professions',
        'sidebar.featured_cities': 'Featured Cities',
        'sidebar.platform_stats': 'Platform Statistics',
        'stats.total_cv': 'Total CVs',
        'stats.active_seekers': 'Active Job Seekers',
        'stats.new_this_week': 'New This Week',
        'stats.total_views': 'Total Views',
        'stats.matches': 'Successful Matches',
        'sidebar.no_job_finders': 'No hires yet.',
        'sidebar.employers': 'Employers',
        'sidebar.most_viewed': 'Most Viewed CVs',
        'sidebar.no_data': 'No data yet.',
        'sidebar.no_featured': 'No featured items yet.',
        'feed.list_title': 'Kartvizid List',
        'feed.sort': 'SORT',
        'feed.no_results': 'No results found.',
        'feed.reset_filters': 'Reset Filters',
        'feed.prev': 'Previous',
        'feed.next': 'Next',
        'feed.page': 'Page',
        'mobile.cancel': 'Cancel',
        // Filters
        'filters.categories': 'All Categories',
        'filters.city': 'Select City',
        'filters.experience': 'Experience Level',
        'filters.advanced': 'Advanced Filters',
        'filters.reset': 'Reset',
        'filters.show_more': 'Show More',
        // Footer
        'footer.brand_desc': 'Turkey\'s new generation digital CV and job matching platform. We are here to offer you the most suitable opportunities in your career journey.',
        'footer.usage': 'Site Usage',
        'footer.general_terms': 'General Terms',
        'footer.security': 'Security Tips',
        'footer.faq': 'FAQ',
        'footer.help': 'Help Center',
        'footer.services': 'Services',
        'footer.data_policy': 'Data Policy',
        'footer.kvkk': 'GDPR Info',
        'footer.cookie_policy': 'Cookie Policy',
        'footer.membership_agreement': 'Membership Agreement',
        'footer.data_owner_form': 'Data Subject Application Form',
        'footer.mobile_app': 'Mobile App',
        'footer.mobile_desc': 'Follow job opportunities from your pocket.',
        'footer.copyright': '© 2026 Kartvizid. All rights reserved.',
        // Business Card
        'card.view': 'VIEW',
        'card.years_exp': 'Years Exp',
        'card.email_visible': 'Email Visible',
        'card.phone_visible': 'Phone Visible',
        // Forms
        'form.cv_create_title': 'Create Your Digital CV',
        'form.cv_create_subtitle': 'Fill in all details for employers to discover you',
        'form.basic_info': '1. BASIC INFORMATION',
        'form.basic_info_subtitle': 'The face of your profile to the outside world',
        'form.work_pref': '2. JOB PREFERENCES',
        'form.work_pref_subtitle': 'Under what conditions do you want to work?',
        'form.exp_skills': '3. EDUCATION & SKILLS',
        'form.exp_skills_subtitle': 'Academic background and expertise',
        'form.personal': '4. PERSONAL DETAILS',
        'form.personal_subtitle': 'Special conditions and legal details',
        'form.about': '5. INTRODUCE YOURSELF',
        'form.about_subtitle': 'Final touch for employers to know you',
        'form.references': 'REFERENCES',
        'form.references_subtitle': 'References for us to get to know you better',
        'form.required': 'Required',
        'form.optional': 'Optional',
        'form.save': 'Save',
        'form.cancel': 'Cancel',
        // Form Fields
        'form.fullname': 'Full Name',
        'form.profession': 'Profession / Title',
        'form.city': 'City',
        'form.district': 'District',
        'form.experience': 'Experience (Years)',
        'form.work_status': 'Work Status',
        'form.working': 'Working',
        'form.not_working': 'Not Working',
        'form.job_seeking': 'Job Seeking',
        'form.contact_info': 'Contact Information (Optional)',
        'form.email': 'Email Address',
        'form.phone': 'Phone Number',
        'form.visible': 'Visible',
        'form.hidden': 'Hidden',
        'form.work_model': 'Work Model',
        'form.employment_type': 'Employment Type',
        'form.salary_exp': 'Salary Expectation (Net Monthly)',
        'form.monthly_net': 'Monthly Net',
        'form.education_info': 'Education Information',
        'form.languages': 'Foreign Languages',
        'form.certificates': 'Certificates & Courses',
        'form.skills': 'Skills',
        'form.military': 'Military Status',
        'form.driving_license': 'Driving License',
        'form.marital': 'Marital Status',
        'form.travel': 'Travel Status',
        'form.disability': 'Disability Status',
        'form.start_date': 'Notice Period',
        'form.about_me': 'ABOUT',
        'form.add_new': 'Add New',
        'form.add': 'Add',
        // Company Form
        'company.create_title': 'Create Employer Profile',
        'company.create_subtitle': 'Enter corporate details for candidates to know you',
        'company.identity': '1. CORPORATE IDENTITY',
        'company.identity_subtitle': 'The public face of your employer profile',
        'company.logo': 'Logo',
        'company.name': 'Employer / Company Name',
        'company.industry': 'Industry',
        'company.website': 'Website',
        'company.about_section': '2. ABOUT EMPLOYER',
        'company.about_subtitle': 'Describe your culture and vision',
        'company.about_placeholder': 'Tell us about yourself and your company...',
        'company.about_hint': 'This information is important for candidates to know your company.',
        'company.save': 'Save Profile',
        'company.address': 'Address Details',
        'company.country': 'Country',

        // New Form Keys
        'form.work_history': 'WORK EXPERIENCE',
        'form.history_subtitle': 'Your career journey from past to present',
        'form.add_experience': 'Add New Experience',
        'form.currently_working': 'I currently work here',
        'form.institution': 'Institution Name',
        'form.position': 'Position',
        'form.start_date_label': 'Start Date',
        'form.end_date_label': 'End Date',
        'form.university': 'University / School',
        'form.department': 'Department',
        'form.add_education': 'Add Education',
        'form.add_language': 'Add Language',
        'form.cert_name': 'Certificate / Course Name',
        'form.cert_issuer': 'Issuer (Optional)',
        'form.cert_date': 'Date Received',
        'form.add_certificate': 'Add Certificate',
        'form.add_reference': 'Add New Reference',
        'form.add_list': 'Add to List',
        'form.save_publish': 'Save and Publish',
        'form.kvkk_text': 'I confirm the accuracy of the information provided. I consent to the processing of my personal data under GDPR.',
        'success.job_found_title': 'CONGRATULATIONS!',
        'success.job_found_msg': 'We wish you success in your new job! As the Kartvizid family, we are happy to be by your side in your career journey.',
        'success.close_btn': 'THANK YOU',
        'success.card_footer': 'KARTVİZİD GREETING CARD',
        'form.no_skills': 'No skills added yet.',
        'form.about_placeholder': 'Introduce yourself impressively in 1-2 sentences by mentioning your experiences and expertise...',
        'form.fullname_example': 'e.g. John Doe',
        'form.profession_example': 'e.g. Senior React Dev',



        // Profile View
        'profile.cv_title': 'Digital Kartvizid Profile',
        'profile.cv_subtitle': 'All professional and personal details of the candidate',
        'profile.company_title': 'Employer Profile',
        'profile.company_subtitle': 'Corporate information and details',
        'profile.basic_info': '1. BASIC INFORMATION',
        'profile.work_pref': '2. JOB PREFERENCES',
        'profile.work_exp': '3. WORK EXPERIENCE',
        'profile.edu_skills': '4. EDUCATION & SKILLS',
        'profile.personal': '5. PERSONAL DETAILS',
        'profile.about': '6. ABOUT',
        'profile.references': '7. REFERENCES',
        'profile.contact': '8. CONTACT INFORMATION',
        'profile.download_cv': 'Download my CV',
        'profile.share_cv': 'Share my CV',
        'profile.job_found': '🎉 I FOUND A JOB',
        'profile.request_sent': 'Request Sent',
        'profile.cancel_request': 'Cancel Request',
        'profile.contact_request': 'Contact',
        'profile.contact_open': 'Contact Info Open',
        'profile.warning_hidden': 'You cannot see personal details before your contact request is approved.',
        'profile.approve_request': 'Approve Request',
        'profile.reject_request': 'Reject',
        'profile.hide_contact': '🚫 HIDE CONTACT INFO',
        'profile.approved_msg': '✅ Contact request approved.',
        'profile.rejected_msg': 'You rejected the contact request from',
        'profile.undo_reject': 'APPROVE REQUEST',
        'profile.close': 'CLOSE',
        'profile.settings': 'Settings',
        'profile.logout': 'Log Out',

        // Notifications
        'notif.title': 'All Notifications',
        'notif.clear_all': 'CLEAR NOTIFICATIONS',
        'notif.empty': 'No notifications yet',
        'notif.view_profile': 'View Profile',
        'notif.approved': 'Approved',
        'notif.rejected': 'Rejected',
        'notif.pending': 'Pending',
        'notif.sent_request': 'wants to contact you. Company:',
        'notif.req_approved': 'approved your contact request. You can now see their contact info.',
        'notif.req_rejected': 'rejected your contact request.',
        'notif.you_approved': 'You approved the contact request from',
        'notif.you_rejected': 'You rejected the contact request from',

        // Common & Values
        'common.none': 'None',
        'common.no_problem': 'No Problem',
        'common.immediately': 'Immediately',
        'common.done': 'Done',
        'common.ongoing': 'Ongoing',
        'errors.no_about': 'Candidate has not added an intro.',
        'errors.no_exp': 'No work experience added.',
        'errors.no_ref': 'No references added.',
        'errors.no_contact': 'No contact info added.',

        // Mappings
        'emp.full_time': 'Full Time',
        'emp.part_time': 'Part Time',
        'emp.project': 'Project Based',
        'work.office': 'Office',
        'work.remote': 'Remote',
        'work.hybrid': 'Hybrid',
        'military.done': 'Done',
        'military.exempt': 'Exempt',
        'military.postponed': 'Postponed',
        'military.not_obligated': 'Not Obligated',
        'marital.single': 'Single',
        'marital.married': 'Married',
        'grad.graduated': 'Graduated',
        'grad.student': 'Student',
        'lang.english': 'English',
        'lang.german': 'German',
        'lang.french': 'French',
        'lang.spanish': 'Spanish',
        'lang.turkish': 'Turkish',
        'lang.russian': 'Russian',
        'lang.arabic': 'Arabic',
        'level.beginner': 'Beginner',
        'level.intermediate': 'Intermediate',
        'level.advanced': 'Advanced',
        'level.native': 'Native',
        'travel.yes': 'Can Travel',
        'travel.no': 'Cannot Travel',

        'sort.default': 'Default',
        'sort.newest': 'Newest',
        'sort.oldest': 'Oldest',
        'promo.premium_title': 'Premium Privilege',
        'promo.premium_desc': 'Stand out, get noticed. Remove speed limits in your career.',
        'promo.employer_title': 'Pinpoint Talent',
        'promo.employer_desc': 'Don\'t waste time with ads. Find the professional you are looking for directly.',
        'promo.seeker_title': 'Let Jobs Find You',
        'promo.seeker_desc': 'Don\'t search, let them discover you. Let your profile work for you.',
        'promo.tips_title': 'Professional Tips',
        'promo.tips_desc': 'Discover expert advice for a perfect first impression.',
        'account.title': 'My Account',
        'account.settings': 'Settings',
        'account.appearance': 'Appearance',
        'account.dark': 'Dark',
        'account.light': 'Light',
        'account.sign_out': 'Sign Out',
        'account.promo_text': 'CREATE YOUR DIGITAL BUSINESSCARD AND START BEING DISCOVERED BY EMPLOYERS IMMEDIATELY!',
        'settings.header_title': 'Account Settings',
        'settings.header_subtitle': 'Manage your profile and security preferences',
        'settings.account_summary': 'Account Summary',
        'settings.email_label': 'Email',
        'settings.member_since': 'Member Since',
        'settings.user_id': 'User ID',
        'settings.delete_account': 'Delete Account',
        'settings.delete_desc_emp': 'Your employer profile and all data will be permanently deleted.',
        'settings.delete_desc_seek': 'Your CV, applications, and profile will be permanently deleted.',
        'settings.delete_warning': 'Warning: This action cannot be undone. You will lose access to all your data after deletion.',
        'settings.delete_btn': 'Delete Account',
        'settings.delete_confirm_title': 'Are you sure you want to delete your account?',
        'settings.delete_confirm_desc_emp': 'This action cannot be undone. Your employer profile and all data will be permanently deleted.',
        'settings.delete_confirm_desc_seek': 'This action cannot be undone. Your CV, profile, and all data will be permanently deleted.',
        'settings.delete_confirm_yes': 'Yes, Delete My Account',
        'settings.change_email': 'Change Email',
        'settings.new_email': 'New email address',
        'settings.update': 'Update',
        'settings.change_password': 'Change Password',
        'settings.new_password': 'New password',
        'settings.new_password_confirm': 'New password (again)',
        'settings.update_password': 'Update Password',
        'settings.notif_email_title': 'Email Notifications',
        'settings.notif_email_desc': 'Receive emails about important updates and activities.',
        'settings.notif_marketing_title': 'Marketing Messages',
        'settings.notif_marketing_desc': 'Receive information about new features and campaigns.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Intern',
        'edu.high_school': 'High School',
        'edu.associate': 'Associate Degree',
        'edu.bachelor': 'Bachelor\'s Degree',
        'edu.master': 'Master\'s Degree',
        'edu.doctorate': 'Doctorate',
        'grad.dropped_out': 'Dropped Out',
        'notice.immediately': 'Immediately',
        'notice.2_weeks': '2 Weeks',
        'notice.1_month': '1 Month',
        'notice.2_months_plus': '2 Months+',
        'disability.yes': 'Yes',
        'disability.no': 'No',

        'travel.cannot_travel': 'Cannot Travel',
        'filter.apply': 'Apply Filters',
        'filter.search_prof_placeholder': 'Search Position (e.g. Software, Waiter...)',
        'filter.search_city_placeholder': 'Search City (e.g. Istanbul, Antalya...)',
        'filter.salary_title': 'SALARY EXPECTATION (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Start searching...',
        'filter.no_results_dropdown': 'No results found...',
        'filter.all_reset': 'All (Reset)',
        'filter.subtitle': 'List the results that best match your criteria in detail',
        'filter.profession_label': 'POSITION / PROFESSION',
        'filter.location_label': 'LOCATION / CITY',
        'filter.work_model_label': 'Work Model',
        'filter.emp_type_label': 'Employment Type',
        'filter.edu_level_label': 'Education Level',
        'filter.grad_status_label': 'Graduation Status',
        'filter.exp_level_label': 'Experience Level',
        'filter.lang_label': 'Foreign Language',
        'filter.lang_level_label': 'Language Level',
        'filter.travel_status_label': 'Travel Status',
        'filter.marital_status_label': 'Marital Status',
        'filter.disability_status_label': 'Disability Status',
        'filter.driver_license_label': 'Driver License',
        'filter.military_status_label': 'Military Status',
        'filter.skills_label': 'Key Skills',
    },
    de: {
        'settings.general': 'Allgemein',
        'settings.language': 'Sprachauswahl',
        'settings.language_desc': 'Ändern Sie die Anzeigesprache der Anwendung.',
        'settings.save': 'Speichern',
        'settings.cancel': 'Abbrechen',
        'settings.account': 'Konto',
        'settings.security': 'Sicherheit',
        'settings.notifications': 'Benachrichtigungen',
        'nav.search_placeholder': 'Suche Beruf, Name oder Stadt...',
        'nav.employer_profile': 'Arbeitgeberprofil',
        'nav.create_cv': 'Lebenslauf erstellen',
        'nav.fix_cv': 'Lebenslauf bearbeiten',
        'nav.employer': 'Arbeitgeber',
        'nav.job_seeker': 'Arbeitssuchend',
        'sidebar.job_finders': 'Auf Kartvizid eingestellt',
        'sidebar.popular_professions': 'Beliebte Berufe',
        'sidebar.featured_cities': 'Ausgewählte Städte',
        'sidebar.platform_stats': 'Plattformstatistiken',
        'stats.total_cv': 'Gesamtlebensläufe',
        'stats.active_seekers': 'Aktive Arbeitssuchende',
        'stats.new_this_week': 'Neu diese Woche',
        'stats.total_views': 'Gesamtansichten',
        'stats.matches': 'Erfolgreiche Übereinstimmungen',
        'sidebar.no_job_finders': 'Noch keine Einstellungen.',
        'sidebar.employers': 'Arbeitgeber',
        'sidebar.most_viewed': 'Meistgesehene Lebensläufe',
        'sidebar.no_data': 'Noch keine Daten.',
        'sidebar.no_featured': 'Noch keine hervorgehobenen Elemente.',
        'feed.list_title': 'Kartvizid Liste',
        'feed.sort': 'SORTIEREN',
        'feed.no_results': 'Keine Ergebnisse gefunden.',
        'feed.reset_filters': 'Filter zurücksetzen',
        'feed.prev': 'Zurück',
        'feed.next': 'Weiter',
        'feed.page': 'Seite',
        'mobile.cancel': 'Abbrechen',
        // Filters
        'filters.categories': 'Alle Kategorien',
        'filters.city': 'Stadt Wählen',
        'filters.experience': 'Erfahrungsstufe',
        'filters.advanced': 'Erweiterte Filter',
        'filters.reset': 'Zurücksetzen',
        'filters.show_more': 'Mehr Anzeigen',
        // Footer
        'footer.brand_desc': 'Türkeis neue Generation der digitalen CV- und Job-Matching-Plattform. Wir sind hier, um Ihnen die besten Möglichkeiten auf Ihrem Karriereweg zu bieten.',
        'footer.usage': 'Seitennutzung',
        'footer.general_terms': 'Allgemeine Bedingungen',
        'footer.security': 'Sicherheitstipps',
        'footer.faq': 'FAQ',
        'footer.help': 'Hilfezentrum',
        'footer.services': 'Dienstleistungen',
        'footer.data_policy': 'Datenrichtlinie',
        'footer.kvkk': 'DSGVO Info',
        'footer.cookie_policy': 'Cookie-Richtlinie',
        'footer.membership_agreement': 'Mitgliedschaftsvereinbarung',
        'footer.data_owner_form': 'Dateneigentümer-Antragsformular',
        'footer.mobile_app': 'Mobile App',
        'footer.mobile_desc': 'Verfolgen Sie Jobmöglichkeiten aus der Tasche.',
        'footer.copyright': '© 2026 Kartvizid. Alle Rechte vorbehalten.',
        // Business Card
        'card.view': 'ANSEHEN',
        'card.years_exp': 'Jahre Erfahrung',
        'card.email_visible': 'E-Mail sichtbar',
        'card.phone_visible': 'Telefon sichtbar',
        // Forms
        'form.cv_create_title': 'Erstellen Sie Ihren digitalen Lebenslauf',
        'form.cv_create_subtitle': 'Füllen Sie alle Details aus, damit Arbeitgeber Sie entdecken',
        'form.basic_info': '1. GRUNDINFORMATIONEN',
        'form.basic_info_subtitle': 'Das Gesicht Ihres Profils zur Außenwelt',
        'form.work_pref': '2. ARBEITSPRÄFERENZEN',
        'form.work_pref_subtitle': 'Unter welchen Bedingungen möchten Sie arbeiten?',
        'form.exp_skills': '3. AUSBILDUNG & FÄHIGKEITEN',
        'form.exp_skills_subtitle': 'Akademischer Hintergrund und Fachkenntnisse',
        'form.personal': '4. PERSÖNLICHE DETAILS',
        'form.personal_subtitle': 'Besondere Bedingungen und rechtliche Details',
        'form.about': '5. STELLEN SIE SICH VOR',
        'form.about_subtitle': 'Letzter Schliff, damit Arbeitgeber Sie kennenlernen',
        'form.references': 'REFERENZEN',
        'form.references_subtitle': 'Referenzen, damit wir Sie besser kennenlernen',
        'form.required': 'Erforderlich',
        'form.optional': 'Optional',
        'form.save': 'Speichern',
        'form.cancel': 'Abbrechen',
        // Form Fields
        'form.fullname': 'Vollständiger Name',
        'form.profession': 'Beruf / Titel',
        'form.city': 'Stadt',
        'form.district': 'Bezirk',
        'form.experience': 'Erfahrung (Jahre)',
        'form.work_status': 'Arbeitsstatus',
        'form.working': 'Berufstätig',
        'form.not_working': 'Nicht Erwerbstätig',
        'form.job_seeking': 'Arbeitssuchend',
        'form.contact_info': 'Kontaktinformationen (Optional)',
        'form.email': 'E-Mail-Adresse',
        'form.phone': 'Telefonnummer',
        'form.visible': 'Sichtbar',
        'form.hidden': 'Versteckt',
        'form.work_model': 'Arbeitsmodell',
        'form.employment_type': 'Beschäftigungsart',
        'form.salary_exp': 'Gehaltsvorstellung (Netto Monatlich)',
        'form.monthly_net': 'Monatlich Netto',
        'form.education_info': 'Bildungsinformationen',
        'form.languages': 'Fremdsprachen',
        'form.certificates': 'Zertifikate & Kurse',
        'form.skills': 'Fähigkeiten',
        'form.military': 'Militärstatus',
        'form.driving_license': 'Führerschein',
        'form.marital': 'Familienstand',
        'form.travel': 'Reisebereitschaft',
        'form.disability': 'Behinderungsstatus',
        'form.start_date': 'Kündigungsfrist',
        'form.about_me': 'ÜBER MICH',
        'form.add_new': 'Neu Hinzufügen',
        'form.add': 'Hinzufügen',
        // Company Form
        'company.create_title': 'Arbeitgeberprofil Erstellen',
        'company.create_subtitle': 'Geben Sie Unternehmensdetails ein',
        'company.identity': '1. UNTERNEHMENSIDENTITÄT',
        'company.logo': 'Logo',
        'company.name': 'Firmenname',
        'company.industry': 'Branche',
        'company.website': 'Webseite',
        'company.save': 'Profil Speichern',

        // New Form Keys
        'form.work_history': 'BERUFSERFAHRUNG',
        'form.history_subtitle': 'Ihre Karriere im Überblick',
        'form.add_experience': 'Neue Erfahrung hinzufügen',
        'form.currently_working': 'Ich arbeite derzeit hier',
        'form.institution': 'Einrichtung',
        'form.position': 'Position',
        'form.start_date_label': 'Startdatum',
        'form.end_date_label': 'Enddatum',
        'form.university': 'Universität / Schule',
        'form.department': 'Fachbereich',
        'form.add_education': 'Ausbildung hinzufügen',
        'form.add_language': 'Sprache hinzufügen',
        'form.cert_name': 'Zertifikat / Kursname',
        'form.cert_issuer': 'Aussteller (Optional)',
        'form.cert_date': 'Erhalten am',
        'form.add_certificate': 'Zertifikat hinzufügen',
        'form.add_reference': 'Neue Referenz hinzufügen',
        'form.add_list': 'Zur Liste hinzufügen',
        'form.save_publish': 'Speichern und Veröffentlichen',
        'form.kvkk_text': 'Ich bestätige die Richtigkeit der Angaben. Ich stimme der Verarbeitung meiner Daten gemäß DSGVO zu.',
        'success.job_found_title': 'HERZLICHEN GLÜCKWUNSCH!',
        'success.job_found_msg': 'Wir wünschen Ihnen viel Erfolg im neuen Job! Als Kartvizid-Familie freuen wir uns, Sie auf Ihrem Karriereweg begleitet zu haben.',
        'success.close_btn': 'DANKE SCHÖN',
        'success.card_footer': 'KARTVİZİD GLÜCKWUNSCHKARTE',
        'form.no_skills': 'Noch keine Fähigkeiten hinzugefügt.',
        'form.about_placeholder': 'Stellen Sie sich in 1-2 Sätzen eindrucksvoll vor, indem Sie Ihre Erfahrungen und Fachkenntnisse erwähnen...',
        'form.fullname_example': 'z.B. Schmidt Heinz',
        'form.profession_example': 'z.B. Senior React Entwickler',



        // Profile View
        'profile.cv_title': 'Digitales Kartvizid Profil',
        'profile.cv_subtitle': 'Alle beruflichen und persönlichen Details des Kandidaten',
        'profile.company_title': 'Arbeitgeberprofil',
        'profile.basic_info': '1. GRUNDINFORMATIONEN',
        'profile.work_pref': '2. ARBEITSPRÄFERENZEN',
        'profile.work_exp': '3. BERUFSERFAHRUNG',
        'profile.edu_skills': '4. AUSBILDUNG & FÄHIGKEITEN',
        'profile.personal': '5. PERSÖNLICHE DETAILS',
        'profile.about': '6. ÜBER MICH',
        'profile.references': '7. REFERENZEN',
        'profile.contact': '8. KONTAKT',
        'profile.download_cv': 'CV Herunterladen',
        'profile.share_cv': 'CV Teilen',
        'profile.contact_request': 'Kontaktieren',
        'profile.contact_open': 'Kontakt Offen',
        'profile.warning_hidden': 'Sie können keine persönlichen Daten sehen, bevor Ihre Kontaktanfrage genehmigt wurde.',
        'profile.approve_request': 'Genehmigen',
        'profile.reject_request': 'Ablehnen',

        // Common & Values
        'common.none': 'Keine',
        'common.no_problem': 'Kein Problem',
        'common.immediately': 'Sofort',
        'common.done': 'Erledigt',
        'common.ongoing': 'Laufend',
        'errors.no_about': 'Keine Vorstellung hinzugefügt.',
        'errors.no_exp': 'Keine Berufserfahrung.',
        'errors.no_ref': 'Keine Referenzen.',
        'errors.no_contact': 'Keine Kontaktinfo.',

        // Mappings
        'emp.full_time': 'Vollzeit',
        'emp.part_time': 'Teilzeit',
        'emp.project': 'Projektbasiert',
        'work.office': 'Büro',
        'work.remote': 'Remote',
        'work.hybrid': 'Hybrid',
        'military.done': 'Erledigt',
        'military.exempt': 'Befreit',
        'military.postponed': 'Aufgeschoben', // Assuming translation or keep similar structure
        'military.not_obligated': 'Nicht Verpflichtet',
        'marital.single': 'Ledig',
        'marital.married': 'Verheiratet',
        'grad.graduated': 'Absolvent',
        'grad.student': 'Student',
        'lang.english': 'Englisch',
        'lang.german': 'Deutsch',
        'lang.french': 'Französisch',
        'lang.spanish': 'Spanisch',
        'lang.turkish': 'Türkisch',
        'lang.russian': 'Russisch',
        'lang.arabic': 'Arabisch',
        'level.beginner': 'Anfänger',
        'level.intermediate': 'Mittelstufe',
        'level.advanced': 'Fortgeschritten',
        'level.native': 'Muttersprache',
        'travel.yes': 'Reisebereit',
        'travel.no': 'Nicht Reisebereit',
        'travel.no_barrier': 'Kein Reisehindernis',
        'sort.default': 'Standard',
        'sort.newest': 'Neueste',
        'sort.oldest': 'Älteste',
        'promo.premium_title': 'Premium Privileg',
        'promo.premium_desc': 'Heben Sie sich ab. Entfernen Sie Geschwindigkeitsbegrenzungen in Ihrer Karriere.',
        'promo.employer_title': 'Talent auf den Punkt',
        'promo.employer_desc': 'Verschwenden Sie keine Zeit mit Anzeigen. Finden Sie den gesuchten Profi direkt.',
        'promo.seeker_title': 'Lass Jobs dich finden',
        'promo.seeker_desc': 'Suche nicht, lass dich entdecken. Lass dein Profil für dich arbeiten.',
        'promo.tips_title': 'Profi-Tipps',
        'promo.tips_desc': 'Entdecken Sie Expertenratschläge für einen perfekten ersten Eindruck.',
        'account.title': 'Mein Konto',
        'account.settings': 'Einstellungen',
        'account.appearance': 'Aussehen',
        'account.dark': 'Dunkel',
        'account.light': 'Hell',
        'account.sign_out': 'Abmelden',
        'account.promo_text': 'ERSTELLEN SIE IHRE DIGITALE VISITENKARTE UND LASSEN SIE SICH SOFORT VON ARBEITGEBERN ENTDECKEN!',
        'settings.header_title': 'Kontoeinstellungen',
        'settings.header_subtitle': 'Verwalten Sie Ihre Profil- und Sicherheitspräferenzen',
        'settings.account_summary': 'Kontoübersicht',
        'settings.email_label': 'E-Mail',
        'settings.member_since': 'Mitglied seit',
        'settings.user_id': 'Benutzer-ID',
        'settings.delete_account': 'Konto löschen',
        'settings.delete_desc_emp': 'Ihr Arbeitgeberprofil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_desc_seek': 'Ihr Lebenslauf, Ihre Bewerbungen und Ihr Profil werden dauerhaft gelöscht.',
        'settings.delete_warning': 'Warnung: Diese Aktion kann nicht rückgängig gemacht werden. Sie verlieren nach dem Löschen den Zugriff auf alle Ihre Daten.',
        'settings.delete_btn': 'Konto Löschen',
        'settings.delete_confirm_title': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
        'settings.delete_confirm_desc_emp': 'Diese Aktion kann nicht rückgängig gemacht werden. Ihr Arbeitgeberprofil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_confirm_desc_seek': 'Diese Aktion kann nicht rückgängig gemacht werden. Ihr Lebenslauf, Ihr Profil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_confirm_yes': 'Ja, Mein Konto Löschen',
        'settings.change_email': 'E-Mail Ändern',
        'settings.new_email': 'Neue E-Mail-Adresse',
        'settings.update': 'Aktualisieren',
        'settings.change_password': 'Passwort Ändern',
        'settings.new_password': 'Neues Passwort',
        'settings.new_password_confirm': 'Neues Passwort (wiederholen)',
        'settings.update_password': 'Passwort Aktualisieren',
        'settings.notif_email_title': 'E-Mail-Benachrichtigungen',
        'settings.notif_email_desc': 'Erhalten Sie E-Mails zu wichtigen Aktualisierungen und Aktivitäten.',
        'settings.notif_marketing_title': 'Marketing-Nachrichten',
        'settings.notif_marketing_desc': 'Erhalten Sie Informationen zu neuen Funktionen und Kampagnen.',
        // Filter Options
        'emp.freelance': 'Freiberuflich',
        'emp.intern': 'Praktikant',
        'edu.high_school': 'Gymnasium',
        'edu.associate': 'Assoziierter Abschluss',
        'edu.bachelor': 'Bachelor-Abschluss',
        'edu.master': 'Master-Abschluss',
        'edu.doctorate': 'Doktorat',
        'grad.dropped_out': 'Abgebrochen',
        'notice.immediately': 'Sofort',
        'notice.2_weeks': '2 Wochen',
        'notice.1_month': '1 Monat',
        'notice.2_months_plus': '2 Monate+',
        'disability.yes': 'Ja',
        'disability.no': 'Nein',

        'travel.cannot_travel': 'Kann nicht reisen',
        'filter.apply': 'Filter Anwenden',
        'filter.search_prof_placeholder': 'Position suchen (z.B. Software, Kellner...)',
        'filter.search_city_placeholder': 'Stadt suchen (z.B. Istanbul, Antalya...)',
        'filter.salary_title': 'GEHALTSVORSTELLUNG (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Suche starten...',
        'filter.no_results_dropdown': 'Keine Ergebnisse gefunden...',
        'filter.all_reset': 'Alle (Zurücksetzen)',
        'filter.subtitle': 'Listen Sie die Ergebnisse im Detail auf, die Ihren Kriterien am besten entsprechen',
        'filter.profession_label': 'POSITION / BERUF',
        'filter.location_label': 'STANDORT / STADT',
        'filter.work_model_label': 'Arbeitsmodell',
        'filter.emp_type_label': 'Beschäftigungsart',
        'filter.edu_level_label': 'Bildungsniveau',
        'filter.grad_status_label': 'Abschlussstatus',
        'filter.exp_level_label': 'Erfahrungsstufe',
        'filter.lang_label': 'Fremdsprache',
        'filter.lang_level_label': 'Sprachniveau',
        'filter.travel_status_label': 'Reisestatus',
        'filter.marital_status_label': 'Familienstand',
        'filter.disability_status_label': 'Behinderungsstatus',
        'filter.driver_license_label': 'Führerschein',
        'filter.military_status_label': 'Militärstatus',
        'filter.skills_label': 'Schlüsselfähigkeiten',
        'profile.close': 'SCHLIEẞEN',

        // Notifications
        'notif.title': 'Alle Benachrichtigungen',
        'notif.clear_all': 'ALLES LÖSCHEN',
        'notif.empty': 'Keine Benachrichtigungen',
        'notif.view_profile': 'Profil Ansehen',
    },
    fr: {
        'settings.general': 'Général',
        'settings.language': 'Sélection de la langue',
        'settings.language_desc': 'Changez la langue d\'affichage de l\'application.',
        'settings.save': 'Enregistrer',
        'settings.cancel': 'Annuler',
        'settings.account': 'Compte',
        'settings.security': 'Sécurité',
        'settings.notifications': 'Notifications',
        'nav.search_placeholder': 'Rechercher profession, nom ou ville...',
        'nav.employer_profile': 'Profil employeur',
        'nav.create_cv': 'Créer un CV',
        'nav.fix_cv': 'Modifier le CV',
        'nav.employer': 'Employeur',
        'nav.job_seeker': 'Chercheur d\'emploi',
        'sidebar.job_finders': 'Embauché sur Kartvizid',
        'sidebar.popular_professions': 'Professions populaires',
        'sidebar.featured_cities': 'Villes en vedette',
        'sidebar.platform_stats': 'Statistiques de la plateforme',
        'stats.total_cv': 'Total CV',
        'stats.active_seekers': 'Chercheurs actifs',
        'stats.new_this_week': 'Nouveau cette semaine',
        'stats.total_views': 'Vues totales',
        'stats.matches': 'Correspondances réussies',
        'sidebar.no_job_finders': 'Pas encore d\'embauches.',
        'sidebar.employers': 'Employeurs',
        'sidebar.most_viewed': 'CV les plus consultés',
        'sidebar.no_data': 'Pas encore de données.',
        'sidebar.no_featured': 'Pas encore d\'éléments en vedette.',
        'feed.list_title': 'Liste Kartvizid',
        'feed.sort': 'TRIER',
        'feed.no_results': 'Aucun résultat trouvé.',
        'feed.reset_filters': 'Réinitialiser les filtres',
        'feed.prev': 'Précédent',
        'feed.next': 'Suivant',
        'feed.page': 'Page',
        'mobile.cancel': 'Annuler',
        // Filters
        'filters.categories': 'Toutes Catégories',
        'filters.city': 'Choisir Ville',
        'filters.experience': 'Niveau d\'Expérience',
        'filters.advanced': 'Filtres Avancés',
        'filters.reset': 'Réinitialiser',
        'filters.show_more': 'Montrer Plus',
        // Footer (French) - Simplified for brevity
        'footer.brand_desc': 'Plateforme numérique de CV et de jumelage d\'emploi nouvelle génération en Turquie.',
        'footer.usage': 'Utilisation du site',
        'footer.copyright': '© 2026 Kartvizid. Tous droits réservés.',
        'card.view': 'VOIR',
        'card.years_exp': 'Ans d\'Exp',
        'form.cv_create_title': 'Créer votre CV numérique',
        'form.basic_info': '1. INFORMATIONS DE BASE',
        'form.save': 'Enregistrer',
        'form.cancel': 'Annuler',
        'form.fullname': 'Nom Complet',
        'form.profession': 'Profession',
        'form.city': 'Ville',
        'form.experience': 'Expérience',
        'company.create_title': 'Créer Profil Employeur',
        'profile.cv_title': 'Profil Kartvizid Numérique',
        'profile.about': '6. À PROPOS',
        'profile.references': '7. RÉFÉRENCES',
        'profile.contact': '8. CONTACT',
        'profile.download_cv': 'Télécharger CV',
        'profile.share_cv': 'Partager CV',
        'profile.cv_subtitle': 'Tous les détails professionnels et personnels du candidat',
        'profile.contact_request': 'Contacter',
        'profile.contact_open': 'Contact Ouvert',
        'profile.warning_hidden': 'Vous ne pouvez pas voir les détails personnels avant l\'approbation de votre demande de contact.',
        'profile.approve_request': 'Approuver',
        'profile.reject_request': 'Rejeter',
        'notif.title': 'Toutes les Notifications',

        // Common & Values
        'common.none': 'Aucun',
        'common.no_problem': 'Pas de problème',
        'common.immediately': 'Immédiatement',
        'common.done': 'Fait',
        'common.ongoing': 'En cours',
        'errors.no_about': 'Aucune introduction.',
        'errors.no_exp': 'Aucune expérience.',
        'errors.no_ref': 'Aucune référence.',
        'errors.no_contact': 'Aucun contact.',

        // Mappings
        'emp.full_time': 'Temps Plein',
        'emp.part_time': 'Temps Partiel',
        'emp.project': 'Projet',
        'work.office': 'Bureau',
        'work.remote': 'Télétravail',
        'work.hybrid': 'Hybride',
        'military.done': 'Fait',
        'military.exempt': 'Exempté',
        'military.postponed': 'Reporté',
        'marital.single': 'Célibataire',
        'marital.married': 'Marié',
        'grad.graduated': 'Diplômé',
        'grad.student': 'Étudiant',
        'lang.english': 'Anglais',
        'lang.german': 'Allemand',
        'lang.french': 'Français',
        'lang.spanish': 'Espagnol',
        'lang.turkish': 'Turc',
        'lang.russian': 'Russe',
        'lang.arabic': 'Arabe',
        'level.beginner': 'Débutant',
        'level.intermediate': 'Intermédiaire',
        'level.advanced': 'Avancé',
        'level.native': 'Langue Maternelle',
        'travel.yes': 'Peut Voyager',
        'travel.no': 'Ne Peut Pas Voyager',
        'travel.no_barrier': 'Pas d\'Obstacle au Voyage',
        'sort.default': 'Défaut',
        'sort.newest': 'Plus Récents',
        'sort.oldest': 'Plus Anciens',
        'promo.premium_title': 'Privilège Premium',
        'promo.premium_desc': 'Démarquez-vous. Supprimez les limites de vitesse dans votre carrière.',
        'promo.employer_title': 'Talent Ciblé',
        'promo.employer_desc': 'Ne perdez pas de temps avec des annonces. Trouvez directement le professionnel que vous cherchez.',
        'promo.seeker_title': 'Laissez les emplois vous trouver',
        'promo.seeker_desc': 'Ne cherchez pas, laissez-les vous découvrir. Laissez votre profil travailler pour vous.',
        'promo.tips_title': 'Conseils de Pro',
        'promo.tips_desc': 'Découvrez les conseils d\'experts pour une première impression parfaite.',
        'account.title': 'Mon Compte',
        'account.settings': 'Paramètres',
        'account.appearance': 'Apparence',
        'account.dark': 'Sombre',
        'account.light': 'Clair',
        'account.sign_out': 'Se Déconnecter',

        'account.promo_text': 'CRÉEZ VOTRE CARTE DE VISITE NUMÉRIQUE ET COMMENCEZ À ÊTRE DÉCOUVERT PAR LES EMPLOYEURS IMMÉDIATEMENT !',
        'settings.header_title': 'Paramètres du Compte',
        'settings.header_subtitle': 'Gérez vos préférences de profil et de sécurité',
        'settings.account_summary': 'Résumé du Compte',
        'settings.email_label': 'E-mail',
        'settings.member_since': 'Membre depuis',
        'settings.user_id': 'ID Utilisateur',
        'settings.delete_account': 'Supprimer le Compte',
        'settings.delete_desc_emp': 'Votre profil employeur et toutes les données seront définitivement supprimés.',
        'settings.delete_desc_seek': 'Votre CV, vos candidatures et votre profil seront définitivement supprimés.',
        'settings.delete_warning': 'Attention : Cette action est irréversible. Vous perdrez l\'accès à toutes vos données après la suppression.',
        'settings.delete_btn': 'Supprimer le Compte',
        'settings.delete_confirm_title': 'Êtes-vous sûr de vouloir supprimer votre compte ?',
        'settings.delete_confirm_desc_emp': 'Cette action est irréversible. Votre profil employeur et toutes les données seront définitivement supprimés.',
        'settings.delete_confirm_desc_seek': 'Cette action est irréversible. Votre CV, votre profil et toutes les données seront définitivement supprimés.',
        'settings.delete_confirm_yes': 'Oui, Supprimer Mon Compte',
        'settings.change_email': 'Changer l\'E-mail',
        'settings.new_email': 'Nouvelle adresse e-mail',
        'settings.update': 'Mettre à jour',
        'settings.change_password': 'Changer le Mot de Passe',
        'settings.new_password': 'Nouveau mot de passe',
        'settings.new_password_confirm': 'Nouveau mot de passe (répéter)',
        'settings.update_password': 'Mettre à jour le Mot de Passe',
        'settings.notif_email_title': 'Notifications par E-mail',
        'settings.notif_email_desc': 'Recevez des e-mails sur les mises à jour et activités importantes.',
        'settings.notif_marketing_title': 'Messages Marketing',
        'settings.notif_marketing_desc': 'Recevez des informations sur les nouvelles fonctionnalités et campagnes.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Stagiaire',
        'edu.high_school': 'Lycée',
        'edu.associate': 'Diplôme Associé',
        'edu.bachelor': 'Licence',
        'edu.master': 'Master',
        'edu.doctorate': 'Doctorat',
        'grad.dropped_out': 'Abandonné',
        'notice.immediately': 'Immédiatement',
        'notice.2_weeks': '2 Semaines',
        'notice.1_month': '1 Mois',
        'notice.2_months_plus': '2 Mois+',
        'success.job_found_title': 'FÉLICITATIONS!',
        'success.job_found_msg': 'Nous vous souhaitons beaucoup de succès dans votre nouvel emploi !',
        'success.close_btn': 'MERCI',
        'success.card_footer': 'CARTE DE VŒUX KARTVİZİD',
        'disability.no': 'Non',

        'travel.cannot_travel': 'Ne peut pas voyager',
        'filter.apply': 'Appliquer les Filtres',
        'filter.search_prof_placeholder': 'Rechercher un poste (ex: Logiciel, Serveur...)',
        'filter.search_city_placeholder': 'Rechercher une ville (ex: Istanbul, Antalya...)',
        'filter.salary_title': 'ATTENTE SALARIALE (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Commencer la recherche...',
        'filter.no_results_dropdown': 'Aucun résultat trouvé...',
        'filter.all_reset': 'Tout (Réinitialiser)',
        'filter.subtitle': 'Listez en détail les résultats qui correspondent le mieux à vos critères',
        'filter.profession_label': 'POSTE / PROFESSION',
        'filter.location_label': 'LIEU / VILLE',
        'filter.work_model_label': 'Modèle de Travail',
        'filter.emp_type_label': 'Type d\'Emploi',
        'filter.edu_level_label': 'Niveau d\'Éducation',
        'filter.grad_status_label': 'Statut de Diplôme',
        'filter.exp_level_label': 'Niveau d\'Expérience',
        'filter.lang_label': 'Langue Étrangère',
        'filter.lang_level_label': 'Niveau de Langue',
        'filter.travel_status_label': 'Statut de Voyage',
        'filter.marital_status_label': 'État Civil',
        'filter.disability_status_label': 'Statut de Handicap',
        'filter.driver_license_label': 'Permis de Conduire',
        'filter.military_status_label': 'Service Militaire',
        'filter.skills_label': 'Compétences Clés',
    },
    es: {
        'settings.general': 'General',
        'settings.language': 'Selección de idioma',
        'settings.language_desc': 'Cambiar el idioma de visualización de la aplicación.',
        'settings.save': 'Guardar',
        'settings.cancel': 'Cancelar',
        'settings.account': 'Cuenta',
        'settings.security': 'Seguridad',
        'settings.notifications': 'Notificaciones',
        'nav.search_placeholder': 'Buscar profesión, nombre o ciudad...',
        'nav.employer_profile': 'Perfil de empleador',
        'nav.create_cv': 'Crear CV',
        'nav.fix_cv': 'Editar CV',
        'nav.employer': 'Empleador',
        'nav.job_seeker': 'Buscador de empleo',
        'sidebar.job_finders': 'Contratado en Kartvizid',
        'sidebar.popular_professions': 'Profesiones populares',
        'sidebar.featured_cities': 'Ciudades destacadas',
        'sidebar.platform_stats': 'Estadísticas de la plataforma',
        'stats.total_cv': 'Total CVs',
        'stats.active_seekers': 'Buscadores activos',
        'stats.new_this_week': 'Nuevo esta semana',
        'stats.total_views': 'Vistas totales',
        'stats.matches': 'Coincidencias exitosas',
        'sidebar.no_job_finders': 'Aún no hay contrataciones.',
        'sidebar.employers': 'Empleadores',
        'sidebar.most_viewed': 'CVs más vistos',
        'sidebar.no_data': 'Aún no hay datos.',
        'sidebar.no_featured': 'Aún no hay elementos destacados.',
        'feed.list_title': 'Lista Kartvizid',
        'feed.sort': 'ORDENAR',
        'feed.no_results': 'No se encontraron resultados.',
        'feed.reset_filters': 'Restablecer filtros',
        'feed.prev': 'Anterior',
        'feed.next': 'Siguiente',
        'feed.page': 'Página',
        'mobile.cancel': 'Cancelar',
        // Filters
        'filters.categories': 'Todas Categorías',
        'filters.city': 'Sel. Ciudad',
        'filters.experience': 'Nivel de Exp.',
        'filters.advanced': 'Filtros Avanzados',
        'filters.reset': 'Reiniciar',
        'filters.show_more': 'Ver Más',
        // Footer (Spanish) - Simplified
        'footer.brand_desc': 'Plataforma de CV digital y emparejamiento laboral de nueva generación en Turquía.',
        'footer.usage': 'Uso del sitio',
        'footer.copyright': '© 2026 Kartvizid. Todos los derechos reservados.',
        'card.view': 'VER',
        'card.years_exp': 'Años Exp',
        'form.cv_create_title': 'Crear su CV digital',
        'form.basic_info': '1. INFORMACIÓN BÁSICA',
        'form.save': 'Guardar',
        'form.cancel': 'Cancelar',
        'form.fullname': 'Nombre Completo',
        'form.profession': 'Profesión',
        'form.city': 'Ciudad',
        'form.experience': 'Experiencia',
        'company.create_title': 'Crear Perfil Empleador',
        'profile.cv_title': 'Perfil Kartvizid Digital',
        'profile.about': '6. ACERCA DE MÍ',
        'profile.references': '7. REFERENCIAS',
        'profile.contact': '8. CONTACTO',
        'profile.download_cv': 'Descargar CV',
        'profile.share_cv': 'Compartir CV',
        'profile.cv_subtitle': 'Todos los detalles profesionales y personales del candidato',
        'profile.contact_request': 'Contactar',
        'profile.contact_open': 'Contacto Abierto',
        'profile.warning_hidden': 'No puedes ver los detalles personales antes de que se apruebe tu solicitud de contacto.',
        'profile.approve_request': 'Aprobar',
        'profile.reject_request': 'Rechazar',
        'notif.title': 'Todas las Notificaciones',

        // Common & Values
        'common.none': 'Ninguno',
        'common.no_problem': 'Sin problemas',
        'common.immediately': 'Inmediatamente',
        'common.done': 'Hecho',
        'common.ongoing': 'En curso',
        'errors.no_about': 'Sin introducción.',
        'errors.no_exp': 'Sin experiencia.',
        'errors.no_ref': 'Sin referencias.',
        'errors.no_contact': 'Sin contacto.',

        // Mappings
        'emp.full_time': 'Tiempo Completo',
        'emp.part_time': 'Medio Tiempo',
        'emp.project': 'Proyecto',
        'work.office': 'Oficina',
        'work.remote': 'Remoto',
        'work.hybrid': 'Híbrido',
        'military.done': 'Hecho',
        'military.exempt': 'Exento',
        'military.postponed': 'Pospuesto',
        'marital.single': 'Soltero',
        'marital.married': 'Casado',
        'grad.graduated': 'Graduado',
        'grad.student': 'Estudiante',
        'lang.english': 'Inglés',
        'lang.german': 'Alemán',
        'lang.french': 'Francés',
        'lang.spanish': 'Español',
        'lang.turkish': 'Turco',
        'lang.russian': 'Ruso',
        'lang.arabic': 'Árabe',
        'level.beginner': 'Principiante',
        'level.intermediate': 'Intermedio',
        'level.advanced': 'Avanzado',
        'level.native': 'Nativo',
        'travel.yes': 'Puede Viajar',
        'travel.no': 'No Puede Viajar',
        'travel.no_barrier': 'Sin Barreras de Viaje',
        'sort.default': 'Por Defecto',
        'sort.newest': 'Más Recientes',
        'sort.oldest': 'Más Antiguos',
        'promo.premium_title': 'Privilegio Premium',
        'promo.premium_desc': 'Destaca. Elimina los límites de velocidad en tu carrera.',
        'promo.employer_title': 'Talento Exacto',
        'promo.employer_desc': 'No pierdas tiempo con anuncios. Encuentra directamente al profesional que buscas.',
        'promo.seeker_title': 'Deja que te encuentren',
        'promo.seeker_desc': 'No busques, deja que te descubran. Deja que tu perfil trabaje por ti.',
        'promo.tips_title': 'Consejos Profesionales',
        'promo.tips_desc': 'Descubre consejos de expertos para una primera impresión perfecta.',
        'account.title': 'Mi Cuenta',
        'account.settings': 'Configuración',
        'account.appearance': 'Apariencia',
        'account.dark': 'Oscuro',
        'account.light': 'Claro',
        'account.sign_out': 'Cerrar Sesión',

        'account.promo_text': '¡CREA TU TARJETA DE VISITA DIGITAL Y COMIENZA A SER DESCUBIERTO POR LOS EMPLEADORES INMEDIATAMENTE!',
        'settings.header_title': 'Configuración de la Cuenta',
        'settings.header_subtitle': 'Gestiona tus preferencias de perfil y seguridad',
        'settings.account_summary': 'Resumen de la Cuenta',
        'settings.email_label': 'Correo electrónico',
        'settings.member_since': 'Miembro desde',
        'settings.user_id': 'ID de Usuario',
        'settings.delete_account': 'Eliminar Cuenta',
        'settings.delete_desc_emp': 'Tu perfil de empleador y todos los datos se eliminarán permanentemente.',
        'settings.delete_desc_seek': 'Tu CV, solicitudes y perfil se eliminarán permanentemente.',
        'settings.delete_warning': 'Advertencia: Esta acción no se puede deshacer. Perderás el acceso a todos tus datos después de la eliminación.',
        'settings.delete_btn': 'Eliminar Cuenta',
        'settings.delete_confirm_title': '¿Estás seguro de que deseas eliminar tu cuenta?',
        'settings.delete_confirm_desc_emp': 'Esta acción no se puede deshacer. Tu perfil de empleador y todos los datos se eliminarán permanentemente.',
        'settings.delete_confirm_desc_seek': 'Esta acción no se puede deshacer. Tu CV, perfil y todos los datos se eliminarán permanentemente.',
        'settings.delete_confirm_yes': 'Sí, Eliminar Mi Cuenta',
        'settings.change_email': 'Cambiar Correo',
        'settings.new_email': 'Nueva dirección de correo',
        'settings.update': 'Actualizar',
        'settings.change_password': 'Cambiar Contraseña',
        'settings.new_password': 'Nueva contraseña',
        'settings.new_password_confirm': 'Nueva contraseña (repetir)',
        'settings.update_password': 'Actualizar Contraseña',
        'settings.notif_email_title': 'Notificaciones por Correo',
        'settings.notif_email_desc': 'Recibe correos sobre actualizaciones y actividades importantes.',
        'settings.notif_marketing_title': 'Mensajes de Marketing',
        'settings.notif_marketing_desc': 'Recibe información sobre nuevas funciones y campañas.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Pasante',
        'edu.high_school': 'Bachillerato',
        'edu.associate': 'Grado Asociado',
        'edu.bachelor': 'Licenciatura',
        'edu.master': 'Maestría',
        'edu.doctorate': 'Doctorado',
        'grad.dropped_out': 'Abandonado',
        'notice.immediately': 'Inmediatamente',
        'notice.2_weeks': '2 Semanas',
        'notice.1_month': '1 Mes',
        'notice.2_months_plus': '2 Meses+',
        'success.job_found_title': '¡FELICITACIONES!',
        'success.job_found_msg': '¡Le deseamos mucho éxito en su nuevo trabajo!',
        'success.close_btn': 'GRACIAS',
        'success.card_footer': 'TARJETA DE FELICITACIÓN KARTVİZİD',
        'disability.no': 'No',

        'travel.cannot_travel': 'No Puede Viajar',
        'filter.apply': 'Aplicar Filtros',
        'filter.search_prof_placeholder': 'Buscar Posición (ej: Software, Camarero...)',
        'filter.search_city_placeholder': 'Buscar Ciudad (ej: Estambul, Antalya...)',
        'filter.salary_title': 'EXPECTATIVA SALARIAL (₺)',
        'filter.salary_min': 'Mín',
        'filter.salary_max': 'Máx',
        'filter.search_placeholder_dropdown': 'Empezar a buscar...',
        'filter.no_results_dropdown': 'No se encontraron resultados...',
        'filter.all_reset': 'Todo (Reiniciar)',
        'filter.subtitle': 'Lista en detalle los resultados que mejor se adapten a tus criterios',
        'filter.profession_label': 'POSICIÓN / PROFESIÓN',
        'filter.location_label': 'UBICACIÓN / CIUDAD',
        'filter.work_model_label': 'Modelo de Trabajo',
        'filter.emp_type_label': 'Tipo de Empleo',
        'filter.edu_level_label': 'Nivel Educativo',
        'filter.grad_status_label': 'Estado de Graduación',
        'filter.exp_level_label': 'Nivel de Experiencia',
        'filter.lang_label': 'Idioma Extranjero',
        'filter.lang_level_label': 'Nivel de Idioma',
        'filter.travel_status_label': 'Estado de Viaje',
        'filter.marital_status_label': 'Estado Civil',
        'filter.disability_status_label': 'Estado de Discapacidad',
        'filter.driver_license_label': 'Licencia de Conducir',
        'filter.military_status_label': 'Estado Militar',
        'filter.skills_label': 'Habilidades Clave',
    },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    // Try to get from localStorage, default to 'tr'
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('app_language');
        return (saved as Language) || 'tr';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);
        // Optional: Reload implementation if deep i18n requires it, 
        // but for React state based i18n, just updating context is enough.
    };

    const t = (key: string): string => {
        const translation = translations[language]?.[key];
        // Fallback to Turkish if missing
        return translation || translations['tr']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
