import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en' | 'de' | 'fr' | 'es' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translation dictionary for demo/infrastructure purposes
// In a real app, this would be imported from separate JSON files
const translations: Record<Language, Record<string, string>> = {
    tr: {
        'settings.general': 'Genel',
        'settings.language': 'Dil Seçimi',
        'settings.language_desc': 'Uygulamanın görüntüleme dilini değiştirin.',
        'settings.save': 'Kaydet',
        'settings.cancel': 'Vazgeç',
        'settings.account': 'Hesap',
        'settings.security': 'Güvenlik',
        'settings.notifications': 'Bildirimler',
        'nav.search_placeholder': 'Meslek, Şehir, İsim Ara',
        'nav.employer_profile': 'İş Veren Profili',
        'nav.create_cv': 'CV Oluştur',
        'nav.fix_cv': 'CV\'yi Düzelt',
        'nav.employer': 'İş Veren',
        'nav.job_seeker': 'İş Arayan',
        'sidebar.job_finders': 'Kartvizid\'te İş Bulanlar',
        'sidebar.popular_professions': 'Talep Gören Meslekler',
        'sidebar.featured_cities': 'Öne Çıkan Şehirler',
        'sidebar.platform_stats': 'Kartvizid İstatistikleri',
        'stats.total_cv': 'Toplam CV',
        'stats.active_seekers': 'Aktif İş Arayan',
        'stats.new_this_week': 'Bu Hafta Yeni',
        'stats.total_views': 'Toplam Görüntülenme',
        'stats.matches': 'Başarılı Eşleşme',
        'sidebar.no_job_finders': 'Henüz iş bulan yok.',
        'sidebar.employers': 'İş Verenler',
        'sidebar.most_viewed': 'En Çok Görüntülenen Kartvizidler',
        'sidebar.no_data': 'Henüz veri yok.',
        'sidebar.no_featured': 'Henüz öne çıkan yok.',
        'feed.list_title': 'Kartvizid Listesi',
        'feed.sort': 'SIRALAMA',
        'feed.no_results': 'Sonuç bulunamadı.',
        'feed.reset_filters': 'Filtreleri Sıfırla',
        'feed.prev': 'Önceki',
        'feed.next': 'Sonraki',
        'feed.page': 'Sayfa',
        'feed.end_title': 'Sonuna Ulaştınız',
        'feed.end_desc': 'CV\'leri tekrar gözden geçirin.',
        'feed.searching_more': 'Daha Fazla Sonuç Aranıyor...',
        'menu.job_seekers': 'İş Arayanlar',
        'menu.kartvizid': 'Kartvizid',
        'mobile.cancel': 'İptal',
        // Filters
        'filters.categories': 'Tüm Kategoriler',
        'filters.city': 'Şehir Seçin',
        'filters.experience': 'Deneyim Seviyesi',
        'filters.advanced': 'Gelişmiş Filtreler',
        'filters.reset': 'Sıfırla',
        'filters.show_more': 'Daha Fazla Göster',
        // Footer
        'footer.brand_desc': 'Türkiye\'nin yeni nesil dijital CV ve iş eşleşme platformu. Kariyer yolculuğunuzda size en uygun fırsatları sunmak için buradayız.',
        'footer.usage': 'Site Kullanımı',
        'footer.general_terms': 'Genel Koşullar',
        'footer.security': 'Güvenlik İpuçları',
        'footer.faq': 'Sıkça Sorulan Sorular',
        'footer.help': 'Yardım Merkezi',
        'footer.services': 'Hizmetlerimiz',
        'footer.data_policy': 'Veri Politikamız',
        'footer.kvkk': 'KVKK Aydınlatma',
        'footer.cookie_policy': 'Çerez Politikası',
        'footer.membership_agreement': 'Üyelik Sözleşmesi',
        'footer.data_owner_form': 'Veri Sahibi Başvuru Formu',
        'footer.mobile_app': 'Mobil Uygulama',
        'footer.mobile_desc': 'İş fırsatlarını cebinizden takip edin.',
        'footer.copyright': '© 2026 Kartvizid. Tüm hakları saklıdır.',
        // Business Card
        'card.view': 'GÖRÜNTÜLE',
        'card.years_exp': 'Yıl Deneyim',
        'card.email_visible': 'E-posta Görünür',
        'card.phone_visible': 'Telefon Görünür',
        // Forms
        'form.cv_create_title': 'CV\'ni Oluştur',
        'form.cv_create_subtitle': 'Hızlıca Profilini Oluştur, Hemen Keşfedil',
        'form.about': '5. KENDİNİZİ TANITIN',
        'form.about_subtitle': 'Kendinizden kısaca bahsederek profilinizi öne çıkarın',
        'form.basic_info_clean': 'TEMEL BİLGİLER',
        'form.work_pref_clean': 'İŞ TERCİHLERİ',
        'form.exp_skills_clean': 'EĞİTİM & YETENEKLER',
        'form.education_skills': 'EĞİTİM & YETENEKLER',
        'form.personal_clean': 'KİŞİSEL DETAYLAR',
        'form.about_clean': 'HAKKINDA',
        'form.references': 'REFERANSLAR',
        'form.references_subtitle': 'Sizi daha yakından tanımamız için referanslarınız',
        'form.basic_info_subtitle': 'Dış dünyaya görünen profil yüzünüz',
        'form.work_pref_subtitle': 'Hangi şartlarda çalışmak istiyorsunuz?',
        'form.exp_skills_subtitle': 'Akademik geçmiş ve uzmanlık alanlarınız',
        'form.personal_subtitle': 'Özel durumlar ve yasal detaylar',
        'form.history_subtitle': 'Geçmişten günümüze kariyer yolculuğunuz',
        'form.work_history_clean': 'İŞ DENEYİMİ',
        'form.internships_clean': 'STAJ DENEYİMİ',
        'form.education_info_clean': 'EĞİTİM BİLGİLERİ',
        'form.education_info_subtitle': 'Akademik geçmişinizi ekleyin',
        'form.contact_info_clean': 'İLETİŞİM BİLGİLERİ',
        'form.contact_info_subtitle': 'İletişim tercihlerinizi yönetin',
        'form.required': 'Zorunlu',
        'form.optional': 'Opsiyonel',
        'form.save': 'Kaydet',
        'form.cancel': 'Vazgeç',
        // Form Fields
        'form.fullname': 'Ad Soyad',
        'form.profession': 'Meslek / Ünvan',
        'form.city': 'Şehir',
        'form.district': 'İlçe',
        'form.experience': 'Tecrübe (Yıl)',
        'form.work_status': 'Çalışma Durumu',
        'form.working': 'Çalışıyorum',
        'form.not_working': 'Çalışmıyorum',
        'form.job_seeking': 'İş Arıyorum',
        'form.contact_info': 'İletişim Bilgileri (Opsiyonel)',
        'form.email': 'E-posta Adresi',
        'form.phone': 'Telefon Numarası',
        'form.visible': 'Görünür',
        'form.hidden': 'Gizli',
        'form.work_model': 'Çalışma Modeli',
        'form.employment_type': 'Çalışma Şekli',
        'form.salary_exp': 'Maaş Beklentisi (Aylık Net)',
        'form.monthly_net': 'Aylık Net',
        'form.education_info': 'Eğitim Bilgileri',
        'form.languages': 'Yabancı Diller',
        'form.certificates': 'Sertifikalar & Kurslar',
        'form.skills': 'Uzmanlık Alanları',
        'form.military': 'Askerlik Durumu',
        'form.driving_license': 'Sürücü Belgesi',
        'form.marital': 'Medeni Durum',
        'form.travel': 'Seyahat Durumu',
        'form.disability': 'Engellilik Durumu',
        'form.start_date': 'İşe Başlama Süresi',
        'form.about_me': 'HAKKINDA',
        'form.add_new': 'Yeni Ekle',
        'form.add': 'Ekle',
        'form.add_experience': 'Yeni Deneyim Ekle',
        'form.currently_working': 'Şu an burada çalışıyorum',
        'form.institution': 'Kurum Adı',
        'form.position': 'Pozisyon',
        'form.start_date_label': 'Başlangıç',
        'form.end_date_label': 'Bitiş',
        'form.university': 'Üniversite / Okul',
        'form.department': 'Bölüm',
        'form.add_education': 'Eğitim Ekle',
        'form.add_language': 'Dil Ekle',
        'form.cert_name': 'Sertifika / Kurs Adı',
        'form.cert_issuer': 'Veren Kurum (Opsiyonel)',
        'form.cert_date': 'Alınan Tarih',
        'form.add_certificate': 'Sertifika Ekle',
        'form.add_reference': 'Yeni Referans Ekle',
        'form.add_list': 'Listeye Ekle',
        'form.save_publish': 'Kaydet ve Yayına Al',
        'form.completion_rate': 'CV TAMAMLANMA ORANI',
        'form.kvkk_text': "KVKK Aydınlatma Metni'ni okudum ve onaylıyorum.",
        'form.no_skills': 'Henüz yetenek eklemediniz.',
        'form.about_placeholder': 'Deneyimlerinizden ve uzmanlığınızdan bahsederek kendinizi 1-2 cümleyle etkileyici bir şekilde tanıtın...',
        'form.skills_placeholder': 'React, Proje Yönetimi, SQL, Figma...',
        'form.fullname_example': ' ',
        'form.profession_example': ' ',
        'form.profession_hint': 'Birden fazla ünvan için virgül (,) ile ayırınız.',
        'form.cv_photo': 'CV Fotoğrafı',
        'form.birth_date': 'Doğum Tarihi',
        'form.preferred_city': 'Tercih Edilen Şehir',
        'form.preferred_roles': 'Tercih Edilen Alanlar',
        'form.roles_placeholder': "Alan ekleyip Enter'a basın...",
        'form.currently_working_short': 'Devam Ediyor',
        'form.add_internship': 'Staj Ekle',
        'form.internships': 'STAJ DENEYİMLERİ',
        'form.internships_subtitle': 'Staj deneyimlerinizi ekleyin',
        'form.contact_hint_text': 'Yanındaki yuvarlak kutucuğu işaretlemediğiniz sürece iletişim bilgileriniz profilinizde görünmez.',
        'common.year': 'Yıl',
        'common.month': 'Ay',
        'common.new_graduate': 'Yeni Mezun',
        'common.less_than_year': '1 Yıldan Az',
        'success.job_found_title': 'TEBRİKLER!',
        'success.job_found_msg': 'Yeni işinizde başarılar dileriz! Kartvizid ailesi olarak kariyer yolculuğunuzda yanınızda olmaktan mutluluk duyduk.',
        'success.close_btn': 'TEŞEKKÜRLER',
        'success.card_footer': 'KARTVİZİD TEBRİK KARTI',
        // Company Form
        'company.create_title': 'İş Veren Profilinizi Oluşturun',
        'company.create_subtitle': 'Adayların sizi tanıması için kurumsal bilgilerinizi girin',
        'company.identity': '1. KURUMSAL KİMLİK',
        'company.identity_subtitle': 'İş veren profilinizin görünen yüzü',
        'company.logo': 'Logo',
        'company.name': 'İş Veren / Kurum Adı',
        'company.industry': 'Sektör',
        'company.website': 'Web Sitesi',
        'menu.home': 'Ana Sayfa',
        'menu.search': 'Ara',
        'menu.create': 'Oluştur',
        'menu.notifications': 'Bildirimler',
        'menu.profile': 'Profil',
        'company.about_section': '2. İŞ VEREN HAKKINDA',
        'company.about_subtitle': 'Kültürünüzü ve vizyonunuzu anlatın',
        'company.about_placeholder': 'Kendinizden ve şirketinizden bahsedin...',
        'company.about_hint': 'Bu bilgiler adayların şirketinizi tanıması için önemlidir.',
        'company.save': 'Profili Kaydet',
        'company.address': 'Adres Detayı',
        'company.address_long': 'Mahalle, Cadde, Sokak No...',
        'company.country': 'Ülke',
        'company.name_placeholder': 'Acme A.Ş.',
        'company.industry_placeholder': 'Teknoloji',
        'company.district_placeholder': 'İlçe Seçiniz',
        'company.city_first': 'Önce Şehir Seçin',
        'company.address_placeholder': 'Mahalle, Cadde, Sokak No...',
        'errors.logo_required': 'Devam etmek için lütfen şirket logosu yükleyiniz. (Zorunlu)',
        'errors.company_name_required': 'Lütfen şirket adı giriniz. (Zorunlu)',
        'errors.city_required': 'Lütfen şehir seçiniz. (Zorunlu)',
        'errors.district_required': 'Lütfen ilçe seçiniz. (Zorunlu)',
        'errors.industry_required': 'Lütfen sektör giriniz. (Zorunlu)',
        'errors.description_required': 'Lütfen hakkında yazısı ekleyiniz. (Zorunlu)',
        'errors.no_about_company': 'Şirket hakkında bilgi girilmemiş.',
        'errors.employer_required': 'İş Veren Hesabı Gerekli',
        'errors.employer_desc': 'Başka bir iş arayanla iletişime geçmek için önce iş veren hesabı oluşturmalısınız.',
        'errors.no_intern': 'Henüz staj deneyimi eklenmemiş.',
        'nav.menu': 'Menü',
        'nav.tagline': 'dijital cv & doğru eşleşme',
        'nav.my_cv': 'Kartvizidim',
        'nav.saved_cvs': 'Kaydettiklerim',
        'notif.a_user': 'Bir kullanıcı',
        'notif.contact_request_label': 'İletişim İsteği',
        'notif.employer_desc': 'Kaydettiğiniz adaylara iletişim isteği gönderdiğinizde, süreç buradan takip edilir. Yeni adayları keşfedin!',
        'notif.jobseeker_desc_strong': 'Kartvizid\'de işverenler ilan açmaz, doğrudan sizinle iletişime geçer.',
        'notif.jobseeker_desc_text': 'Özgeçmişinizi güncel tutun ve ilk iş görüşmesi davetinizi bekleyin.',
        'notif.title_approved': 'İletişim İsteği Onaylandı',
        'notif.title_rejected': 'İstek Sonuçlandı',
        'account.promo_text': 'DİJİTAL KARTVİZİD\'İNİ OLUŞTURUP İŞVERENLER TARAFINDAN KEŞFEDİLMEYE HEMEN BAŞLA!',
        'auth.login': 'Giriş Yap',
        'auth.signup': 'Kayıt Ol',
        'auth.signin_title': 'Tekrar Hoş Geldiniz',
        'auth.signin_desc': 'Hesabınıza erişmek için bilgilerinizi girin.',
        'auth.signup_title': 'Hesap Türünü Seçin',
        'auth.signup_desc': 'Size uygun hesap türünü seçerek aramıza katılın.',
        'auth.forgot_password': 'Şifremi Unuttum',
        'auth.email_label': 'E-posta',
        'auth.password_label': 'Şifre',
        'auth.signin_btn': 'Giriş Yap',
        'auth.signup_btn': 'Kayıt Ol',
        'auth.no_account': 'Henüz hesabınız yok mu?',
        'auth.have_account': 'Zaten bir hesabınız var mı?',
        'auth.signup_now': 'Hemen Kayıt Ol',
        'auth.job_seeker_title': 'İş Arıyorum',
        'auth.employer_title': 'Eleman Arıyorum',
        'auth.job_seeker_desc': 'Kariyer fırsatlarını yakalayın',
        'auth.employer_desc': 'Sektörün en iyilerini bulun',
        'auth.or': 'veya',
        'auth.signin_google': 'Google ile Giriş Yap',
        'auth.signup_google': 'Google ile Kayıt Ol',
        'auth.signin_apple': 'Apple ile Giriş Yap',
        'auth.signup_apple': 'Apple ile Kayıt Ol',
        'auth.success_signup': 'Kayıt Başarılı!',
        'auth.success_signup_desc': 'Lütfen e-posta adresinizi doğrulayın. Hesabınızı aktifleştirmek için gelen kutunuzu kontrol edin.',
        'errors.no_cert': 'Henüz sertifika veya kurs eklenmemiş.',
        'common.got_it': 'Anladım',
        'common.success': 'Başarılı',
        'common.processing': 'İşleniyor...',
        'common.link_copied': 'Link başarıyla kopyalandı!',
        'auth.selected_type': 'Seçilen Hesap Türü',
        'form.work_period': 'ÇALIŞMA DÖNEMİ',
        'form.intern_role': 'STAJ POZİSYONU',
        'form.intern_period': 'STAJ DÖNEMİ',
        'profile.employer_view_desc': 'Bu işveren iletişim bilgilerinizi görüntüleyebilir.',
        'profile.undo_reject_desc': 'Fikrinizi değiştirdiyseniz isteği tekrar onaylayabilirsiniz.',





        // Profile View (CV & Company)
        'profile.cv_title': 'Dijital Kartvizid Profili',
        'profile.cv_subtitle': 'KAPSAMLI KARİYER ÖZETİ VE PROFESYONEL YETKİNLİKLER',
        'profile.company_title': 'İş Veren Profili',
        'profile.company_subtitle': 'Kurumsal bilgiler ve detaylar',
        'profile.basic_info': 'TEMEL BİLGİLER',
        'profile.work_pref': 'İŞ TERCİHLERİ',
        'profile.work_exp': 'İŞ DENEYİMİ',
        'profile.edu_skills': 'EĞİTİM & YETENEKLER',
        'profile.personal': 'KİŞİSEL DETAYLAR',
        'profile.about': 'HAKKINDA',
        'profile.references': 'REFERANSLAR',
        'profile.contact': 'İLETİŞİM BİLGİLERİ',
        'profile.download_cv': 'CV\'mi İndir',
        'profile.share_cv': 'CV\'mi Paylaş',
        'profile.job_found': '🎉 İŞİMİ BULDUM',
        'profile.request_sent': 'İstek Gönderildi',
        'profile.cancel_request': 'İsteği İptal Et',
        'profile.contact_request': 'İletişime Geç',
        'profile.send_message': 'Mesaj Gönder',
        'profile.close': 'KAPAT',
        'profile.settings': 'Ayarlar',
        'profile.logout': 'Çıkış Yap',
        'messages.title': 'İş Görüşmeleri',
        'messages.subtitle': 'Görüşmelerinizi buradan takip edin.',
        'messages.no_conversations': 'Henüz Mesaj Yok',
        'messages.empty_title': 'Henüz Bir Görüşme Başlamadı',
        'messages.empty_desc': 'İşverenler sizinle iletişime geçtiğinde veya siz bir sohbet başlattığınızda mesajlarınız burada görünecektir.',
        'messages.click_to_start': 'Sohbeti başlatın...',
        'messages.type_placeholder': 'Mesajınızı buraya yazın...',

        // Notifications
        'notif.title': 'Tüm Bildirimler',
        'notif.clear_all': 'BİLDİRİMLERİ TEMİZLE',
        'notif.empty': 'Henüz bildiriminiz yok',
        'notif.view_profile': 'Profili Gör',
        'notif.approved': 'Onaylandı',
        'notif.rejected': 'Reddedildi',
        'notif.pending': 'Bekliyor',
        'notif.you_rejected': 'kişisinin iletişim isteğini reddettiniz.',

        // Common & Values
        'common.none': 'Yok',
        'common.no_problem': 'Sorun Yok',
        'common.immediately': 'Hemen',
        'common.done': 'Yapıldı',
        'common.ongoing': 'Devam Ediyor',
        'errors.no_about': 'Aday kendini tanıtacak bir yazı eklememiş.',
        'errors.no_exp': 'İş deneyimi eklenmemiş.',
        'common.years_experience': 'yıl deneyim',
        'errors.ref_name_required': 'Referans Eklemek için İsim ve Kurum girmelisiniz.',
        'errors.photo_upload_failed': 'Fotoğraf yüklenirken hata oluştu',
        'errors.kvkk_required': 'Lütfen KVKK metnini okuyup onaylayınız.',
        'errors.photo_about_required': 'İşverenlerin sizi fark edebilmesi ve olumlu dönüş alabilmeniz için Fotoğraf ve Hakkımda kısımlarını doldurmanız çok önemlidir. Lütfen daha iyi bir izlenim bırakmak için bu alanları doldurup tekrar deneyin.',
        'common.info_msg': 'Bilgi Mesajı',
        'common.missing_info': 'Eksik Bilgiler Var',
        'common.please_note': 'Lütfen dikkate alınız:',
        'common.please_fill': 'Lütfen aşağıdaki alanları doldurunuz:',
        'common.ok_fill': 'Tamam, Dolduracağım',
        'errors.no_ref': 'Referans eklenmemiş.',
        'errors.no_contact': 'İletişim bilgisi girilmemiş.',

        // Mappings
        'emp.full_time': 'Tam Zamanlı',
        'emp.part_time': 'Yarı Zamanlı',
        'emp.project': 'Proje Bazlı',
        'work.office': 'Ofis',
        'work.remote': 'Uzaktan',
        'work.hybrid': 'Hibrit',
        'military.done': 'Yapıldı',
        'military.exempt': 'Muaf',
        'military.postponed': 'Tecilli',
        'military.not_obligated': 'Yükümlü Değil',
        'marital.single': 'Bekar',
        'marital.married': 'Evli',
        'grad.graduated': 'Mezun',
        'grad.student': 'Öğrenci',
        'lang.english': 'İngilizce',
        'lang.german': 'Almanca',
        'lang.french': 'Fransızca',
        'lang.spanish': 'İspanyolca',
        'lang.turkish': 'Türkçe',
        'lang.russian': 'Rusça',
        'lang.arabic': 'Arapça',
        'level.beginner': 'Başlangıç',
        'level.intermediate': 'Orta',
        'level.advanced': 'İleri',
        'level.native': 'Anadil',
        'travel.yes': 'Seyahat Edebilir',
        'travel.no': 'Seyahat Edemez',
        'travel.no_barrier': 'Seyahat Engeli Yok',
        'sort.default': 'Varsayılan',
        'sort.newest': 'En Yeniler',
        'sort.oldest': 'En Eskiler',
        'promo.premium_title': 'Premium Ayrıcalığı',
        'promo.premium_desc': 'Öne çıkın, fark edilin. Kariyerinizde hız limitlerini kaldırın.',
        'promo.employer_title': 'Nokta Atışı Yetenek',
        'promo.employer_desc': 'İlanla vakit kaybetmeyin. Aradığınız profesyoneli doğrudan bulun.',
        'promo.seeker_title': 'İş Seni Bulsun',
        'promo.seeker_desc': 'Sen arama, onlar seni keşfetsin. Profilin senin yerine çalışsın.',
        'promo.tips_title': 'Profesyonel İpuçları',
        'promo.tips_desc': 'Kusursuz bir ilk izlenim için uzman tavsiyelerini keşfet.',
        'account.title': 'Hesabım',
        'account.settings': 'Ayarlar',
        'account.appearance': 'Görünüm',
        'account.dark': 'Koyu',
        'account.light': 'Aydınlık',
        'account.sign_out': 'Çıkış Yap',
        'settings.header_title': 'Hesap Ayarları',
        'settings.header_subtitle': 'Profil ve güvenlik tercihlerinizi yönetin',
        'settings.account_summary': 'Hesap Özeti',
        'settings.email_label': 'E-posta',
        'settings.member_since': 'Üyelik Tarihi',
        'settings.user_id': 'Kullanıcı ID',
        'settings.delete_account': 'Hesabımı Sil',
        'settings.delete_desc_emp': 'İş veren profiliniz ve tüm verileriniz kalıcı olarak silinir.',
        'settings.delete_desc_seek': 'CV\'niz, başvurularınız ve profiliniz kalıcı olarak silinir.',
        'settings.delete_warning': 'Dikkat: Bu işlem geri alınamaz. Silme işleminden sonra tüm verilerinize erişimi kaybedeceksiniz.',
        'settings.delete_btn': 'Hesabı Sil',
        'settings.delete_confirm_title': 'Hesabınızı silmek istediğinize emin misiniz?',
        'settings.delete_confirm_desc_emp': 'Bu işlem geri alınamaz. İş veren profiliniz ve tüm verileriniz kalıcı olarak silinecektir.',
        'settings.delete_confirm_desc_seek': 'Bu işlem geri alınamaz. CV\'niz, profiliniz ve tüm verileriniz kalıcı olarak silinecektir.',
        'settings.delete_confirm_yes': 'Evet, Hesabımı Sil',
        'settings.change_email': 'E-posta Değiştir',
        'settings.new_email': 'Yeni e-posta adresi',
        'settings.update': 'Güncelle',
        'settings.change_password': 'Şifre Değiştir',
        'settings.new_password': 'Yeni şifre',
        'settings.new_password_confirm': 'Yeni şifre (tekrar)',
        'settings.update_password': 'Şifreyi Güncelle',
        'settings.notif_email_title': 'E-posta Bildirimleri',
        'settings.notif_email_desc': 'Önemli güncellemeler ve aktiviteler hakkında e-posta al.',
        'settings.notif_marketing_title': 'Pazarlama İletileri',
        'settings.notif_marketing_desc': 'Yeni özellikler ve kampanyalar hakkında bilgi ver.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Stajyer',
        'edu.high_school': 'Lise',
        'edu.associate': 'Önlisans',
        'edu.bachelor': 'Lisans',
        'edu.master': 'Yüksek Lisans',
        'edu.doctorate': 'Doktora',
        'grad.dropped_out': 'Terk',
        'notice.immediately': 'Hemen',
        'notice.2_weeks': '2 Hafta',
        'notice.1_month': '1 Ay',
        'notice.2_months_plus': '2 Ay+',
        'disability.yes': 'Var',
        'disability.no': 'Yok',

        'travel.cannot_travel': 'Seyahat Edemem',
        'filter.apply': 'Filtreleri Uygula',
        'filter.search_prof_placeholder': 'Pozisyon Ara (Yazılım, Garson...)',
        'filter.search_city_placeholder': 'Şehir Ara (İstanbul, Antalya...)',
        'filter.salary_title': 'MAAŞ BEKLENTİSİ (₺)',
        'filter.salary_min': 'En Az',
        'filter.salary_max': 'En Çok',
        'filter.search_placeholder_dropdown': 'Aramaya başlayın...',
        'filter.no_results_dropdown': 'Sonuç bulunamadı...',
        'filter.all_reset': 'Tümü (Sıfırla)',
        'filter.subtitle': 'Kriterlerinize en uygun sonuçları detaylı listeleyin',
        'filter.profession_label': 'POZİSYON / MESLEK',
        'filter.location_label': 'LOKASYON / ŞEHİR',
        'filter.work_model_label': 'Çalışma Modeli',
        'filter.emp_type_label': 'Çalışma Şekli',
        'filter.edu_level_label': 'Eğitim Seviyesi',
        'filter.grad_status_label': 'Mezuniyet Durumu',
        'filter.exp_level_label': 'Deneyim Seviyesi',
        'filter.lang_label': 'Yabancı Dil',
        'filter.lang_level_label': 'Dil Seviyesi',
        'filter.travel_status_label': 'Seyahat Durumu',
        'filter.marital_status_label': 'Medeni Durum',
        'filter.disability_status_label': 'Engellilik Durumu',
        'filter.driver_license_label': 'Sürücü Belgesi',
        'filter.military_status_label': 'Askerlik Durumu',
        'filter.skills_label': 'Önemli Yetenekler',
    },
    en: {
        'settings.general': 'General',
        'settings.language': 'Language Selection',
        'settings.language_desc': 'Change the display language of the application.',
        'settings.save': 'Save',
        'settings.cancel': 'Cancel',
        'settings.account': 'Account',
        'settings.security': 'Security',
        'settings.notifications': 'Notifications',
        'nav.search_placeholder': 'Search profession, name or city...',
        'nav.employer_profile': 'Employer Profile',
        'nav.create_cv': 'Create CV',
        'nav.fix_cv': 'Edit CV',
        'nav.employer': 'Employer',
        'nav.job_seeker': 'Job Seeker',
        'sidebar.job_finders': 'Hired on Kartvizid',
        'sidebar.popular_professions': 'Popular Professions',
        'sidebar.featured_cities': 'Featured Cities',
        'sidebar.platform_stats': 'Platform Statistics',
        'stats.total_cv': 'Total CVs',
        'stats.active_seekers': 'Active Job Seekers',
        'stats.new_this_week': 'New This Week',
        'stats.total_views': 'Total Views',
        'stats.matches': 'Successful Matches',
        'sidebar.no_job_finders': 'No hires yet.',
        'sidebar.employers': 'Employers',
        'sidebar.most_viewed': 'Most Viewed CVs',
        'sidebar.no_data': 'No data yet.',
        'sidebar.no_featured': 'No featured items yet.',
        'feed.list_title': 'Kartvizid List',
        'feed.sort': 'SORT',
        'feed.no_results': 'No results found.',
        'feed.reset_filters': 'Reset Filters',
        'feed.prev': 'Previous',
        'feed.next': 'Next',
        'feed.page': 'Page',
        'feed.end_title': 'You\'ve Reached the End',
        'feed.end_desc': 'Review the CVs again.',
        'menu.job_seekers': 'Job Seekers',
        'menu.kartvizid': 'Kartvizid',
        'mobile.cancel': 'Cancel',
        // Filters
        'filters.categories': 'All Categories',
        'filters.city': 'Select City',
        'filters.experience': 'Experience Level',
        'filters.advanced': 'Advanced Filters',
        'filters.reset': 'Reset',
        'filters.show_more': 'Show More',
        // Footer
        'footer.brand_desc': 'Turkey\'s new generation digital CV and job matching platform. We are here to offer you the most suitable opportunities in your career journey.',
        'footer.usage': 'Site Usage',
        'footer.general_terms': 'General Terms',
        'footer.security': 'Security Tips',
        'footer.faq': 'FAQ',
        'footer.help': 'Help Center',
        'footer.services': 'Services',
        'footer.data_policy': 'Data Policy',
        'footer.kvkk': 'GDPR Info',
        'footer.cookie_policy': 'Cookie Policy',
        'footer.membership_agreement': 'Membership Agreement',
        'footer.data_owner_form': 'Data Subject Application Form',
        'footer.mobile_app': 'Mobile App',
        'footer.mobile_desc': 'Follow job opportunities from your pocket.',
        'footer.copyright': '© 2026 Kartvizid. All rights reserved.',
        // Business Card
        'card.view': 'VIEW',
        'card.years_exp': 'Years Exp',
        'card.email_visible': 'Email Visible',
        'card.phone_visible': 'Phone Visible',
        // Forms
        'form.cv_create_title': 'Create Your Digital CV',
        'form.cv_create_subtitle': 'Fill in all details for employers to discover you',
        'form.about': '5. INTRODUCE YOURSELF',
        'form.about_subtitle': 'Final touch for employers to know you',
        'form.basic_info_clean': 'BASIC INFORMATION',
        'form.work_pref_clean': 'JOB PREFERENCES',
        'form.exp_skills_clean': 'EDUCATION & SKILLS',
        'form.education_skills': 'EDUCATION & SKILLS',
        'form.personal_clean': 'PERSONAL DETAILS',
        'form.about_clean': 'ABOUT / SUMMARY',
        'form.references': 'REFERENCES',
        'form.references_subtitle': 'References for us to get to know you better',
        'form.basic_info_subtitle': 'The face of your profile to the outside world',
        'form.work_pref_subtitle': 'Under what conditions do you want to work?',
        'form.exp_skills_subtitle': 'Academic background and expertise',
        'form.personal_subtitle': 'Special conditions and legal details',
        'form.history_subtitle': 'Your career journey from past to present',
        'form.work_history_clean': 'WORK EXPERIENCE',
        'form.internships_clean': 'INTERNSHIPS',
        'form.education_info_clean': 'EDUCATION INFORMATION',
        'form.contact_info_clean': 'CONTACT INFORMATION',
        'form.required': 'Required',
        'form.optional': 'Optional',
        'form.save': 'Save',
        'form.cancel': 'Cancel',
        // Form Fields
        'form.fullname': 'Full Name',
        'form.profession': 'Profession / Title',
        'form.city': 'City',
        'form.district': 'District',
        'form.experience': 'Experience (Years)',
        'form.work_status': 'Work Status',
        'form.working': 'Working',
        'form.not_working': 'Not Working',
        'form.job_seeking': 'Job Seeking',
        'form.contact_info': 'Contact Information (Optional)',
        'form.email': 'Email Address',
        'form.phone': 'Phone Number',
        'form.visible': 'Visible',
        'form.hidden': 'Hidden',
        'form.work_model': 'Work Model',
        'form.employment_type': 'Employment Type',
        'form.salary_exp': 'Salary Expectation (Net Monthly)',
        'form.monthly_net': 'Monthly Net',
        'form.education_info': 'Education Information',
        'form.languages': 'Foreign Languages',
        'form.certificates': 'Certificates & Courses',
        'form.skills': 'Skills',
        'form.military': 'Military Status',
        'form.driving_license': 'Driving License',
        'form.marital': 'Marital Status',
        'form.travel': 'Travel Status',
        'form.disability': 'Disability Status',
        'form.start_date': 'Notice Period',
        'form.about_me': 'ABOUT',
        'form.add_new': 'Add New',
        'form.add': 'Add',
        'form.add_experience': 'Add New Experience',
        'form.currently_working': 'I currently work here',
        'form.institution': 'Institution Name',
        'form.position': 'Position',
        'form.start_date_label': 'Start',
        'form.end_date_label': 'End',
        'form.university': 'University / School',
        'form.department': 'Department',
        'form.add_education': 'Add Education',
        'form.add_language': 'Add Language',
        'form.cert_name': 'Certificate / Course Name',
        'form.cert_issuer': 'Issuer (Optional)',
        'form.cert_date': 'Date Obtained',
        'form.add_certificate': 'Add Certificate',
        'form.add_reference': 'Add New Reference',
        'form.add_list': 'Add to List',
        'form.save_publish': 'Save and Publish',
        'form.completion_rate': 'PROFILE COMPLETION RATE',
        'form.kvkk_text': 'I have read and agree to the KVKK Clarification Text.',
        'form.no_skills': 'You haven\'t added any skills yet.',
        'form.about_placeholder': 'Introduce yourself impressively in 1-2 sentences by mentioning your experiences and expertise...',
        'form.skills_placeholder': 'React, Project Management, SQL, Figma...',
        'form.fullname_example': 'Ex: John Doe',
        'form.profession_example': 'Ex: Senior React Dev',
        'form.birth_date': 'Birth Date',
        'form.preferred_city': 'Preferred City',
        'form.preferred_roles': 'Preferred Roles',
        'form.roles_placeholder': 'Add role and press Enter...',
        'form.currently_working_short': 'Ongoing',
        'form.add_internship': 'Add Internship',
        'form.internships': 'INTERNSHIPS',
        'form.contact_hint_text': 'Your contact information will not appear on your profile unless you check the circular box next to it.',
        'common.year': 'Year',
        'common.month': 'Month',
        'common.new_graduate': 'New Graduate',
        'common.less_than_year': 'Less than 1 Year',
        'success.job_found_title': 'CONGRATULATIONS!',
        'success.job_found_msg': 'We wish you success in your new job! As the Kartvizid family, we were happy to be with you on your career journey.',
        'success.close_btn': 'THANK YOU',
        'success.card_footer': 'KARTVİZİD CONGRATULATIONS CARD',
        // Company Form
        'company.create_title': 'Create Employer Profile',
        'company.create_subtitle': 'Enter corporate details for candidates to know you',
        'company.identity': '1. CORPORATE IDENTITY',
        'company.identity_subtitle': 'The public face of your employer profile',
        'company.logo': 'Logo',
        'company.name': 'Employer / Company Name',
        'company.industry': 'Industry',
        'company.website': 'Website',
        'menu.home': 'Home',
        'menu.search': 'Search',
        'menu.create': 'Create',
        'menu.notifications': 'Notifications',
        'menu.profile': 'Profile',
        'company.about_section': '2. ABOUT EMPLOYER',
        'company.about_subtitle': 'Describe your culture and vision',
        'company.about_placeholder': 'Tell us about yourself and your company...',
        'company.about_hint': 'This information is important for candidates to know your company.',
        'company.save': 'Save Profile',
        'company.address': 'Address Details',
        'company.address_long': 'Neighborhood, Street, No...',
        'company.country': 'Country',
        'company.name_placeholder': 'e.g. Acme Corp.',
        'company.industry_placeholder': 'e.g. Technology',
        'company.district_placeholder': 'Select District',
        'company.city_first': 'Select City First',
        'company.address_placeholder': 'Neighborhood, Street, No...',
        'errors.logo_required': 'Please upload a company logo to continue. (Required)',
        'errors.company_name_required': 'Please enter company name. (Required)',
        'errors.city_required': 'Please select a city. (Required)',
        'errors.district_required': 'Please select a district. (Required)',
        'errors.industry_required': 'Please enter industry. (Required)',
        'errors.description_required': 'Please add an about description. (Required)',
        'errors.no_about_company': 'No information entered about the company.',
        'errors.employer_required': 'Employer Account Required',
        'errors.employer_desc': 'To contact another job seeker, you must first create an employer account.',
        'errors.no_intern': 'No internship experience added yet.',
        'nav.menu': 'Menu',
        'nav.tagline': 'digital cv & right match',
        'nav.my_cv': 'My Kartvizid',
        'nav.saved_cvs': 'Saved CVs',
        'notif.a_user': 'A user',
        'notif.contact_request_label': 'Contact Request',
        'notif.employer_desc': 'When you send contact requests to saved candidates, the process is tracked here. Explore new candidates!',
        'notif.jobseeker_desc_strong': 'On Kartvizid, employers don\'t post jobs, they contact you directly.',
        'notif.jobseeker_desc_text': 'Keep your profile updated and wait for your first interview invitation.',
        'notif.title_approved': 'Contact Request Approved',
        'notif.title_rejected': 'Request Resolved',
        'account.promo_text': 'CREATE YOUR DIGITAL BUSINESS CARD AND START BEING DISCOVERED BY EMPLOYERS IMMEDIATELY!',
        'auth.login': 'Login',
        'auth.signup': 'Sign Up',
        'auth.or': 'or',
        'auth.signin_google': 'Sign In with Google',
        'auth.signup_google': 'Sign Up with Google',
        'auth.signin_apple': 'Sign In with Apple',
        'auth.signup_apple': 'Sign Up with Apple',
        'errors.no_cert': 'No certificates or courses added yet.',
        'common.got_it': 'Got it',
        'common.success': 'Success',
        'common.processing': 'Processing...',
        'common.link_copied': 'Link copied successfully!',
        'auth.selected_type': 'Selected Account Type',
        'form.work_period': 'WORK PERIOD',
        'form.intern_role': 'INTERNSHIP POSITION',
        'form.intern_period': 'INTERNSHIP PERIOD',
        'profile.employer_view_desc': 'This employer can view your contact information.',





        // Profile View
        'profile.cv_title': 'Digital Kartvizid Profile',
        'profile.cv_subtitle': 'COMPREHENSIVE CAREER SUMMARY AND PROFESSIONAL COMPETENCIES',
        'profile.company_title': 'Employer Profile',
        'profile.company_subtitle': 'Corporate information and details',
        'profile.basic_info': 'BASIC INFORMATION',
        'profile.work_pref': 'JOB PREFERENCES',
        'profile.work_exp': 'WORK EXPERIENCE',
        'profile.edu_skills': 'EDUCATION & SKILLS',
        'profile.personal': 'PERSONAL DETAILS',
        'profile.about': 'ABOUT',
        'profile.references': 'REFERENCES',
        'profile.contact': 'CONTACT INFORMATION',
        'profile.download_cv': 'Download my CV',
        'profile.share_cv': 'Share my CV',
        'profile.job_found': '🎉 I FOUND A JOB',
        'profile.request_sent': 'Request Sent',
        'profile.cancel_request': 'Cancel Request',
        'profile.contact_request': 'Contact',
        'profile.close': 'CLOSE',
        'profile.settings': 'Settings',
        'profile.logout': 'Log Out',
        'profile.send_message': 'Send Message',
        'messages.title': 'Job Interviews',
        'messages.subtitle': 'Manage your interviews here.',
        'messages.no_conversations': 'No Messages Yet',
        'messages.empty_title': 'No Conversations Yet',
        'messages.empty_desc': 'When employers contact you or you start a chat, your messages will appear here.',
        'messages.click_to_start': 'Start a conversation...',
        'messages.type_placeholder': 'Type your message...',

        // Notifications
        'notif.title': 'All Notifications',
        'notif.clear_all': 'CLEAR NOTIFICATIONS',
        'notif.empty': 'No notifications yet',
        'notif.view_profile': 'View Profile',
        'notif.approved': 'Approved',
        'notif.rejected': 'Rejected',
        'notif.pending': 'Pending',
        'notif.you_approved': 'You approved the contact request from',
        'notif.you_rejected': 'You rejected the contact request from',

        // Common & Values
        'common.none': 'None',
        'common.no_problem': 'No Problem',
        'common.immediately': 'Immediately',
        'common.done': 'Done',
        'common.ongoing': 'Ongoing',
        'errors.no_about': 'Candidate has not added an intro.',
        'errors.no_exp': 'No work experience added.',
        'common.years_experience': 'years experience',
        'errors.ref_name_required': 'You must enter Name and Company to add a reference.',
        'errors.photo_upload_failed': 'Error uploading photo',
        'errors.kvkk_required': 'Please read and approve the KVKK text.',
        'errors.photo_about_required': 'It is very important to fill in the Photo and About Me sections so that employers can notice you and you can get positive feedback. Please fill in these fields and try again for a better impression.',
        'common.info_msg': 'Information Message',
        'common.missing_info': 'Missing Information',
        'common.please_note': 'Please take note:',
        'common.please_fill': 'Please fill in the following fields:',
        'common.ok_fill': 'Ok, I will fill it',
        'errors.no_ref': 'No references added.',
        'errors.no_contact': 'No contact info added.',

        // Mappings
        'emp.full_time': 'Full Time',
        'emp.part_time': 'Part Time',
        'emp.project': 'Project Based',
        'work.office': 'Office',
        'work.remote': 'Remote',
        'work.hybrid': 'Hybrid',
        'military.done': 'Done',
        'military.exempt': 'Exempt',
        'military.postponed': 'Postponed',
        'military.not_obligated': 'Not Obligated',
        'marital.single': 'Single',
        'marital.married': 'Married',
        'grad.graduated': 'Graduated',
        'grad.student': 'Student',
        'lang.english': 'English',
        'lang.german': 'German',
        'lang.french': 'French',
        'lang.spanish': 'Spanish',
        'lang.turkish': 'Turkish',
        'lang.russian': 'Russian',
        'lang.arabic': 'Arabic',
        'level.beginner': 'Beginner',
        'level.intermediate': 'Intermediate',
        'level.advanced': 'Advanced',
        'level.native': 'Native',
        'travel.yes': 'Can Travel',
        'travel.no': 'Cannot Travel',

        'sort.default': 'Default',
        'sort.newest': 'Newest',
        'sort.oldest': 'Oldest',
        'promo.premium_title': 'Premium Privilege',
        'promo.premium_desc': 'Stand out, get noticed. Remove speed limits in your career.',
        'promo.employer_title': 'Pinpoint Talent',
        'promo.employer_desc': 'Don\'t waste time with ads. Find the professional you are looking for directly.',
        'promo.seeker_title': 'Let Jobs Find You',
        'promo.seeker_desc': 'Don\'t search, let them discover you. Let your profile work for you.',
        'promo.tips_title': 'Professional Tips',
        'promo.tips_desc': 'Discover expert advice for a perfect first impression.',
        'account.title': 'My Account',
        'account.settings': 'Settings',
        'account.appearance': 'Appearance',
        'account.dark': 'Dark',
        'account.light': 'Light',
        'account.sign_out': 'Sign Out',
        'settings.header_title': 'Account Settings',
        'settings.header_subtitle': 'Manage your profile and security preferences',
        'settings.account_summary': 'Account Summary',
        'settings.email_label': 'Email',
        'settings.member_since': 'Member Since',
        'settings.user_id': 'User ID',
        'settings.delete_account': 'Delete Account',
        'settings.delete_desc_emp': 'Your employer profile and all data will be permanently deleted.',
        'settings.delete_desc_seek': 'Your CV, applications, and profile will be permanently deleted.',
        'settings.delete_warning': 'Warning: This action cannot be undone. You will lose access to all your data after deletion.',
        'settings.delete_btn': 'Delete Account',
        'settings.delete_confirm_title': 'Are you sure you want to delete your account?',
        'settings.delete_confirm_desc_emp': 'This action cannot be undone. Your employer profile and all data will be permanently deleted.',
        'settings.delete_confirm_desc_seek': 'This action cannot be undone. Your CV, profile, and all data will be permanently deleted.',
        'settings.delete_confirm_yes': 'Yes, Delete My Account',
        'settings.change_email': 'Change Email',
        'settings.new_email': 'New email address',
        'settings.update': 'Update',
        'settings.change_password': 'Change Password',
        'settings.new_password': 'New password',
        'settings.new_password_confirm': 'New password (again)',
        'settings.update_password': 'Update Password',
        'settings.notif_email_title': 'Email Notifications',
        'settings.notif_email_desc': 'Receive emails about important updates and activities.',
        'settings.notif_marketing_title': 'Marketing Messages',
        'settings.notif_marketing_desc': 'Receive information about new features and campaigns.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Intern',
        'edu.high_school': 'High School',
        'edu.associate': 'Associate Degree',
        'edu.bachelor': 'Bachelor\'s Degree',
        'edu.master': 'Master\'s Degree',
        'edu.doctorate': 'Doctorate',
        'grad.dropped_out': 'Dropped Out',
        'notice.immediately': 'Immediately',
        'notice.2_weeks': '2 Weeks',
        'notice.1_month': '1 Month',
        'notice.2_months_plus': '2 Months+',
        'disability.yes': 'Yes',
        'disability.no': 'No',

        'travel.cannot_travel': 'Cannot Travel',
        'filter.apply': 'Apply Filters',
        'filter.search_prof_placeholder': 'Search Position (e.g. Software, Waiter...)',
        'filter.search_city_placeholder': 'Search City (e.g. Istanbul, Antalya...)',
        'filter.salary_title': 'SALARY EXPECTATION (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Start searching...',
        'filter.no_results_dropdown': 'No results found...',
        'filter.all_reset': 'All (Reset)',
        'filter.subtitle': 'List the results that best match your criteria in detail',
        'filter.profession_label': 'POSITION / PROFESSION',
        'filter.location_label': 'LOCATION / CITY',
        'filter.work_model_label': 'Work Model',
        'filter.emp_type_label': 'Employment Type',
        'filter.edu_level_label': 'Education Level',
        'filter.grad_status_label': 'Graduation Status',
        'filter.exp_level_label': 'Experience Level',
        'filter.lang_label': 'Foreign Language',
        'filter.lang_level_label': 'Language Level',
        'filter.travel_status_label': 'Travel Status',
        'filter.marital_status_label': 'Marital Status',
        'filter.disability_status_label': 'Disability Status',
        'filter.driver_license_label': 'Driver License',
        'filter.military_status_label': 'Military Status',
        'filter.skills_label': 'Key Skills',
        'auth.signin_title': 'Welcome Back',
        'auth.signin_desc': 'Enter your credentials to access your account.',
        'auth.signup_title': 'Choose Account Type',
        'auth.signup_desc': 'Choose the account type that suits you and join us.',
        'auth.forgot_password': 'Forgot Password',
        'auth.email_label': 'Email',
        'auth.password_label': 'Password',
        'auth.signin_btn': 'Sign In',
        'auth.signup_btn': 'Sign Up',
        'auth.no_account': "Don't have an account?",
        'auth.have_account': 'Already have an account?',
        'auth.signup_now': 'Sign Up Now',
        'auth.job_seeker_title': 'I am looking for a job',
        'auth.employer_title': 'I am looking for employees',
        'auth.job_seeker_desc': 'Seize career opportunities',
        'auth.employer_desc': 'Find the best in the industry',
        'auth.success_signup': 'Registration Successful!',
        'auth.success_signup_desc': 'Please verify your email address. Check your inbox to activate your account.',
    },
    de: {
        'settings.general': 'Allgemein',
        'settings.language': 'Sprachauswahl',
        'settings.language_desc': 'Ändern Sie die Anzeigesprache der Anwendung.',
        'settings.save': 'Speichern',
        'settings.cancel': 'Abbrechen',
        'settings.account': 'Konto',
        'settings.security': 'Sicherheit',
        'settings.notifications': 'Benachrichtigungen',
        'nav.search_placeholder': 'Suche Beruf, Name oder Stadt...',
        'nav.employer_profile': 'Arbeitgeberprofil',
        'nav.create_cv': 'Lebenslauf erstellen',
        'nav.fix_cv': 'Lebenslauf bearbeiten',
        'nav.employer': 'Arbeitgeber',
        'nav.job_seeker': 'Arbeitssuchend',
        'sidebar.job_finders': 'Auf Kartvizid eingestellt',
        'sidebar.popular_professions': 'Beliebte Berufe',
        'sidebar.featured_cities': 'Ausgewählte Städte',
        'sidebar.platform_stats': 'Plattformstatistiken',
        'stats.total_cv': 'Gesamtlebensläufe',
        'stats.active_seekers': 'Aktive Arbeitssuchende',
        'stats.new_this_week': 'Neu diese Woche',
        'stats.total_views': 'Gesamtansichten',
        'stats.matches': 'Erfolgreiche Übereinstimmungen',
        'sidebar.no_job_finders': 'Noch keine Einstellungen.',
        'sidebar.employers': 'Arbeitgeber',
        'sidebar.most_viewed': 'Meistgesehene Lebensläufe',
        'sidebar.no_data': 'Noch keine Daten.',
        'sidebar.no_featured': 'Noch keine hervorgehobenen Elemente.',
        'feed.list_title': 'Kartvizid Liste',
        'feed.sort': 'SORTIEREN',
        'feed.no_results': 'Keine Ergebnisse gefunden.',
        'feed.reset_filters': 'Filter zurücksetzen',
        'feed.prev': 'Zurück',
        'feed.next': 'Weiter',
        'feed.page': 'Seite',
        'feed.end_title': 'Ende Erreicht',
        'feed.end_desc': 'Überprüfen Sie die Lebensläufe erneut.',
        'menu.job_seekers': 'Jobsuchende',
        'menu.kartvizid': 'Kartvizid',
        'mobile.cancel': 'Abbrechen',
        // Filters
        'filters.categories': 'Alle Kategorien',
        'filters.city': 'Stadt Wählen',
        'filters.experience': 'Erfahrungsstufe',
        'filters.advanced': 'Erweiterte Filter',
        'filters.reset': 'Zurücksetzen',
        'filters.show_more': 'Mehr Anzeigen',
        // Footer
        'footer.brand_desc': 'Türkeis neue Generation der digitalen CV- und Job-Matching-Plattform. Wir sind hier, um Ihnen die besten Möglichkeiten auf Ihrem Karriereweg zu bieten.',
        'footer.usage': 'Seitennutzung',
        'footer.general_terms': 'Allgemeine Bedingungen',
        'footer.security': 'Sicherheitstipps',
        'footer.faq': 'FAQ',
        'footer.help': 'Hilfezentrum',
        'footer.services': 'Dienstleistungen',
        'footer.data_policy': 'Datenrichtlinie',
        'footer.kvkk': 'DSGVO Info',
        'footer.cookie_policy': 'Cookie-Richtlinie',
        'footer.membership_agreement': 'Mitgliedschaftsvereinbarung',
        'footer.data_owner_form': 'Dateneigentümer-Antragsformular',
        'footer.mobile_app': 'Mobile App',
        'footer.mobile_desc': 'Verfolgen Sie Jobmöglichkeiten aus der Tasche.',
        'footer.copyright': '© 2026 Kartvizid. Alle Rechte vorbehalten.',
        // Business Card
        'card.view': 'ANSEHEN',
        'card.years_exp': 'Jahre Erfahrung',
        'card.email_visible': 'E-Mail sichtbar',
        'card.phone_visible': 'Telefon sichtbar',
        // Forms
        'form.cv_create_title': 'Erstellen Sie Ihren digitalen Lebenslauf',
        'form.cv_create_subtitle': 'Füllen Sie alle Details aus, damit Arbeitgeber Sie entdecken',
        'form.about': '5. STELLEN SIE SICH VOR',
        'form.about_subtitle': 'Letzter Schliff, damit Arbeitgeber Sie kennenlernen',
        'form.basic_info_clean': 'GRUNDINFORMATIONEN',
        'form.work_pref_clean': 'ARBEITSPRÄFERENZEN',
        'form.exp_skills_clean': 'AUSBILDUNG & FÄHIGKEITEN',
        'form.education_skills': 'AUSBILDUNG & FÄHIGKEITEN',
        'form.personal_clean': 'PERSÖNLICHE DETAILS',
        'form.about_clean': 'ÜBER MICH / ZUSAMMENFASSUNG',
        'form.references': 'REFERENZEN',
        'form.references_subtitle': 'Referenzen, damit wir Sie besser kennenlernen',
        'form.education_info_subtitle': 'Fügen Sie Ihren akademischen Hintergrund hinzu',
        'form.internships_subtitle': 'Fügen Sie Ihre Praktikumserfahrungen hinzu',
        'form.contact_info_subtitle': 'Verwalten Sie Ihre Kontaktpräferenzen',
        'form.work_history_clean': 'BERUFSERFAHRUNG',
        'form.internships_clean': 'PRAKTIKA',
        'form.education_info_clean': 'AUSBILDUNGSINFORMATIONEN',
        'form.contact_info_clean': 'KONTAKTINFORMATIONEN',
        'form.required': 'Erforderlich',
        'form.optional': 'Optional',
        'form.save': 'Speichern',
        'form.cancel': 'Abbrechen',
        // Form Fields
        'form.fullname': 'Vollständiger Name',
        'form.profession': 'Beruf / Titel',
        'form.city': 'Stadt',
        'form.district': 'Bezirk',
        'form.experience': 'Erfahrung (Jahre)',
        'form.work_status': 'Arbeitsstatus',
        'form.working': 'Berufstätig',
        'form.not_working': 'Nicht Erwerbstätig',
        'form.job_seeking': 'Arbeitssuchend',
        'form.contact_info': 'Kontaktinformationen (Optional)',
        'form.email': 'E-Mail-Adresse',
        'form.phone': 'Telefonnummer',
        'form.visible': 'Sichtbar',
        'form.hidden': 'Versteckt',
        'form.work_model': 'Arbeitsmodell',
        'form.employment_type': 'Beschäftigungsart',
        'form.salary_exp': 'Gehaltsvorstellung (Netto Monatlich)',
        'form.monthly_net': 'Monatlich Netto',
        'form.education_info': 'Bildungsinformationen',
        'form.languages': 'Fremdsprachen',
        'form.certificates': 'Zertifikate & Kurse',
        'form.skills': 'Fähigkeiten',
        'form.military': 'Militärstatus',
        'form.driving_license': 'Führerschein',
        'form.marital': 'Familienstand',
        'form.travel': 'Reisebereitschaft',
        'form.disability': 'Behinderungsstatus',
        'form.start_date': 'Kündigungsfrist',
        'form.about_me': 'ÜBER MICH',
        'form.add_new': 'Neu Hinzufügen',
        'form.add': 'Hinzufügen',
        'form.add_experience': 'Neue Erfahrung hinzufügen',
        'form.currently_working': 'Ich arbeite derzeit hier',
        'form.institution': 'Einrichtung',
        'form.position': 'Position',
        'form.start_date_label': 'Startdatum',
        'form.end_date_label': 'Enddatum',
        'form.university': 'Universität / Schule',
        'form.department': 'Fachbereich',
        'form.add_education': 'Ausbildung hinzufügen',
        'form.add_language': 'Sprache hinzufügen',
        'form.cert_name': 'Zertifikat / Kursname',
        'form.cert_issuer': 'Aussteller (Optional)',
        'form.cert_date': 'Erhalten am',
        'form.add_certificate': 'Zertifikat hinzufügen',
        'form.add_reference': 'Neue Referans hinzufügen',
        'form.add_list': 'Zur Liste hinzufügen',
        'form.save_publish': 'Speichern und Veröffentlichen',
        'form.kvkk_text': 'Ich habe den DSGVO-Beleuchtungstext gelesen und stimme zu.',
        'form.no_skills': 'Noch keine Fähigkeiten hinzugefügt.',
        'form.about_placeholder': 'Stellen Sie sich in 1-2 Sätzen eindrucksvoll vor, indem Sie Ihre Erfahrungen und Fachkenntnisse erwähnen...',
        'form.skills_placeholder': 'React, Projektmanagement, SQL, Figma...',
        'form.fullname_example': 'z.B. Max Mustermann',
        'form.profession_example': 'z.B. Senior React Entwickler',
        'form.birth_date': 'Geburtsdatum',
        'form.preferred_city': 'Bevorzugte Stadt',
        'form.preferred_roles': 'Bevorzugte Bereiche',
        'form.roles_placeholder': "Bereich eingeben und Enter drücken...",
        'form.currently_working_short': 'Fortlaufend',
        'form.add_internship': 'Praktikum hinzufügen',
        'form.internships': 'PRAKTIKUMSERFAHRUNGEN',
        'form.contact_hint_text': 'Ihre Kontaktinformationen werden nur dann in Ihrem Profil angezeigt, wenn Sie das daneben stehende kreisförmige Kästchen ankreuzen.',
        'common.year': 'Jahr',
        'common.month': 'Monat',
        'success.job_found_title': 'HERZLICHEN GLÜCKWUNSCH!',
        'success.job_found_msg': 'Wir wünschen Ihnen viel Erfolg im neuen Job! Als Kartvizid-Familie freuen wir uns, Sie auf Ihrem Karriereweg begleitet zu haben.',
        'success.close_btn': 'DANKE SCHÖN',
        'success.card_footer': 'KARTVİZİD GLÜCKWUNSCHKARTE',
        // Company Form
        'company.create_title': 'Arbeitgeberprofil Erstellen',
        'company.create_subtitle': 'Geben Sie Unternehmensdetails ein',
        'company.identity': '1. UNTERNEHMENSIDENTITÄT',
        'company.logo': 'Logo',
        'company.name': 'Firmenname',
        'company.industry': 'Branche',
        'company.website': 'Webseite',
        'menu.home': 'Startseite',
        'menu.search': 'Suche',
        'menu.create': 'Erstellen',
        'menu.notifications': 'Meldungen',
        'menu.profile': 'Profil',
        'company.save': 'Profil Speichern',





        // Profile View
        'profile.cv_title': 'Digitales Kartvizid Profil',
        'profile.cv_subtitle': 'Alle beruflichen und persönlichen Details des Kandidaten',
        'profile.company_title': 'Arbeitgeberprofil',
        'profile.basic_info': '1. GRUNDINFORMATIONEN',
        'profile.work_pref': '2. ARBEITSPRÄFERENZEN',
        'profile.work_exp': '3. BERUFSERFAHRUNG',
        'profile.edu_skills': '4. AUSBILDUNG & FÄHIGKEITEN',
        'profile.personal': '5. PERSÖNLICHE DETAILS',
        'profile.about': '6. ÜBER MICH',
        'profile.references': '7. REFERENZEN',
        'profile.contact': '8. KONTAKT',
        'profile.download_cv': 'CV Herunterladen',
        'profile.share_cv': 'CV Teilen',
        'profile.contact_request': 'Kontaktieren',

        // Common & Values
        'common.none': 'Keine',
        'common.no_problem': 'Kein Problem',
        'common.immediately': 'Sofort',
        'common.done': 'Erledigt',
        'common.ongoing': 'Laufend',
        'errors.no_about': 'Keine Vorstellung hinzugefügt.',
        'errors.no_exp': 'Keine Berufserfahrung hinzugefügt.',
        'common.years_experience': 'Jahre Erfahrung',
        'errors.ref_name_required': 'Sie müssen Name und Unternehmen eingeben, um eine Referenz hinzuzufügen.',
        'errors.photo_upload_failed': 'Fehler beim Hochladen des Fotos',
        'errors.kvkk_required': 'Bitte lesen und bestätigen Sie den KVKK-Text.',
        'errors.photo_about_required': 'Es ist sehr wichtig, die Abschnitte Foto und Über mich auszufüllen, damit Arbeitgeber auf Sie aufmerksam werden und Sie positives Feedback erhalten können. Bitte füllen Sie diese Felder aus und versuchen Sie es erneut, um einen besseren Eindruck zu hinterlassen.',
        'common.info_msg': 'Informationsmeldung',
        'common.missing_info': 'Fehlende Informationen',
        'common.please_note': 'Bitte beachten Sie:',
        'common.please_fill': 'Bitte füllen Sie die folgenden Felder aus:',
        'common.ok_fill': 'Ok, ich werde es ausfüllen',
        'errors.no_ref': 'Keine Referenzen.',
        'errors.no_contact': 'Keine Kontaktinfo.',

        // Mappings
        'emp.full_time': 'Vollzeit',
        'emp.part_time': 'Teilzeit',
        'emp.project': 'Projektbasiert',
        'work.office': 'Büro',
        'work.remote': 'Remote',
        'work.hybrid': 'Hybrid',
        'military.done': 'Erledigt',
        'military.exempt': 'Befreit',
        'military.postponed': 'Aufgeschoben', // Assuming translation or keep similar structure
        'military.not_obligated': 'Nicht Verpflichtet',
        'marital.single': 'Ledig',
        'marital.married': 'Verheiratet',
        'grad.graduated': 'Absolvent',
        'grad.student': 'Student',
        'lang.english': 'Englisch',
        'lang.german': 'Deutsch',
        'lang.french': 'Französisch',
        'lang.spanish': 'Spanisch',
        'lang.turkish': 'Türkisch',
        'lang.russian': 'Russisch',
        'lang.arabic': 'Arabisch',
        'level.beginner': 'Anfänger',
        'level.intermediate': 'Mittelstufe',
        'level.advanced': 'Fortgeschritten',
        'level.native': 'Muttersprache',
        'travel.yes': 'Reisebereit',
        'travel.no': 'Nicht Reisebereit',
        'travel.no_barrier': 'Kein Reisehindernis',
        'sort.default': 'Standard',
        'sort.newest': 'Neueste',
        'sort.oldest': 'Älteste',
        'promo.premium_title': 'Premium Privileg',
        'promo.premium_desc': 'Heben Sie sich ab. Entfernen Sie Geschwindigkeitsbegrenzungen in Ihrer Karriere.',
        'promo.employer_title': 'Talent auf den Punkt',
        'promo.employer_desc': 'Verschwenden Sie keine Zeit mit Anzeigen. Finden Sie den gesuchten Profi direkt.',
        'promo.seeker_title': 'Lass Jobs dich finden',
        'promo.seeker_desc': 'Suche nicht, lass dich entdecken. Lass dein Profil für dich arbeiten.',
        'promo.tips_title': 'Profi-Tipps',
        'promo.tips_desc': 'Entdecken Sie Expertenratschläge für einen perfekten ersten Eindruck.',
        'account.title': 'Mein Konto',
        'account.settings': 'Einstellungen',
        'account.appearance': 'Aussehen',
        'account.dark': 'Dunkel',
        'account.light': 'Hell',
        'account.sign_out': 'Abmelden',
        'account.promo_text': 'ERSTELLEN SIE IHRE DIGITALE VISITENKARTE UND LASSEN SIE SICH SOFORT VON ARBEITGEBERN ENTDECKEN!',
        'settings.header_title': 'Kontoeinstellungen',
        'settings.header_subtitle': 'Verwalten Sie Ihre Profil- und Sicherheitspräferenzen',
        'settings.account_summary': 'Kontoübersicht',
        'settings.email_label': 'E-Mail',
        'settings.member_since': 'Mitglied seit',
        'settings.user_id': 'Benutzer-ID',
        'settings.delete_account': 'Konto löschen',
        'settings.delete_desc_emp': 'Ihr Arbeitgeberprofil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_desc_seek': 'Ihr Lebenslauf, Ihre Bewerbungen und Ihr Profil werden dauerhaft gelöscht.',
        'settings.delete_warning': 'Warnung: Diese Aktion kann nicht rückgängig gemacht werden. Sie verlieren nach dem Löschen den Zugriff auf alle Ihre Daten.',
        'settings.delete_btn': 'Konto Löschen',
        'settings.delete_confirm_title': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
        'settings.delete_confirm_desc_emp': 'Diese Aktion kann nicht rückgängig gemacht werden. Ihr Arbeitgeberprofil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_confirm_desc_seek': 'Diese Aktion kann nicht rückgängig gemacht werden. Ihr Lebenslauf, Ihr Profil und alle Daten werden dauerhaft gelöscht.',
        'settings.delete_confirm_yes': 'Ja, Mein Konto Löschen',
        'settings.change_email': 'E-Mail Ändern',
        'settings.new_email': 'Neue E-Mail-Adresse',
        'settings.update': 'Aktualisieren',
        'settings.change_password': 'Passwort Ändern',
        'settings.new_password': 'Neues Passwort',
        'settings.new_password_confirm': 'Neues Passwort (wiederholen)',
        'settings.update_password': 'Passwort Aktualisieren',
        'settings.notif_email_title': 'E-Mail-Benachrichtigungen',
        'settings.notif_email_desc': 'Erhalten Sie E-Mails zu wichtigen Aktualisierungen und Aktivitäten.',
        'settings.notif_marketing_title': 'Marketing-Nachrichten',
        'settings.notif_marketing_desc': 'Erhalten Sie Informationen zu neuen Funktionen und Kampagnen.',
        // Filter Options
        'emp.freelance': 'Freiberuflich',
        'emp.intern': 'Praktikant',
        'edu.high_school': 'Gymnasium',
        'edu.associate': 'Assoziierter Abschluss',
        'edu.bachelor': 'Bachelor-Abschluss',
        'edu.master': 'Master-Abschluss',
        'edu.doctorate': 'Doktorat',
        'grad.dropped_out': 'Abgebrochen',
        'notice.immediately': 'Sofort',
        'notice.2_weeks': '2 Wochen',
        'notice.1_month': '1 Monat',
        'notice.2_months_plus': '2 Monate+',
        'disability.yes': 'Ja',
        'disability.no': 'Nein',

        'travel.cannot_travel': 'Kann nicht reisen',
        'filter.apply': 'Filter Anwenden',
        'filter.search_prof_placeholder': 'Position suchen (z.B. Software, Kellner...)',
        'filter.search_city_placeholder': 'Stadt suchen (z.B. Istanbul, Antalya...)',
        'filter.salary_title': 'GEHALTSVORSTELLUNG (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Suche starten...',
        'filter.no_results_dropdown': 'Keine Ergebnisse gefunden...',
        'filter.all_reset': 'Alle (Zurücksetzen)',
        'filter.subtitle': 'Listen Sie die Ergebnisse im Detail auf, die Ihren Kriterien am besten entsprechen',
        'filter.profession_label': 'POSITION / BERUF',
        'filter.location_label': 'STANDORT / STADT',
        'filter.work_model_label': 'Arbeitsmodell',
        'filter.emp_type_label': 'Beschäftigungsart',
        'filter.edu_level_label': 'Bildungsniveau',
        'filter.grad_status_label': 'Abschlussstatus',
        'filter.exp_level_label': 'Erfahrungsstufe',
        'filter.lang_label': 'Fremdsprache',
        'filter.lang_level_label': 'Sprachniveau',
        'filter.travel_status_label': 'Reisestatus',
        'filter.marital_status_label': 'Familienstand',
        'filter.disability_status_label': 'Behinderungsstatus',
        'filter.driver_license_label': 'Führerschein',
        'filter.military_status_label': 'Militärstatus',
        'filter.skills_label': 'Schlüsselfähigkeiten',
        'profile.close': 'SCHLIEẞEN',

        // Notifications
        'notif.title': 'Alle Benachrichtigungen',
        'notif.clear_all': 'ALLES LÖSCHEN',
        'notif.empty': 'Keine Benachrichtigungen',
        'notif.view_profile': 'Profil Ansehen',
        'common.processing': 'Wird verarbeitet...',
        'auth.selected_type': 'Ausgewählter Kontotyp',
        'auth.signin_title': 'Willkommen zurück',
        'auth.signin_desc': 'Geben Sie Ihre Zugangsdaten ein, um auf Ihr Konto zuzugreifen.',
        'auth.signup_title': 'Kontotyp wählen',
        'auth.signup_desc': 'Wählen Sie den für Sie passenden Kontotyp und schließen Sie sich uns an.',
        'auth.forgot_password': 'Passwort vergessen',
        'auth.email_label': 'E-Mail',
        'auth.password_label': 'Passwort',
        'auth.signin_btn': 'Anmelden',
        'auth.signup_btn': 'Registrieren',
        'auth.no_account': 'Noch kein Konto?',
        'auth.have_account': 'Bereits ein Konto?',
        'auth.signup_now': 'Jetzt registrieren',
        'auth.job_seeker_title': 'Ich suche Arbeit',
        'auth.employer_title': 'Ich suche Mitarbeiter',
        'auth.job_seeker_desc': 'Karrierechancen nutzen',
        'auth.employer_desc': 'Finden Sie die Besten der Branche',
        'auth.success_signup': 'Registrierung erfolgreich!',
        'auth.success_signup_desc': 'Bitte bestätigen Sie Ihre E-Mail-Adresse. Überprüfen Sie Ihren Posteingang, um Ihr Konto zu aktivieren.',
    },
    fr: {
        'settings.general': 'Général',
        'settings.language': 'Sélection de la langue',
        'settings.language_desc': 'Changez la langue d\'affichage de l\'application.',
        'settings.save': 'Enregistrer',
        'settings.cancel': 'Annuler',
        'settings.account': 'Compte',
        'settings.security': 'Sécurité',
        'settings.notifications': 'Notifications',
        'nav.search_placeholder': 'Rechercher profession, nom ou ville...',
        'nav.employer_profile': 'Profil employeur',
        'nav.create_cv': 'Créer un CV',
        'nav.fix_cv': 'Modifier le CV',
        'nav.employer': 'Employeur',
        'nav.job_seeker': 'Chercheur d\'emploi',
        'sidebar.job_finders': 'Embauché sur Kartvizid',
        'sidebar.popular_professions': 'Professions populaires',
        'sidebar.featured_cities': 'Villes en vedette',
        'sidebar.platform_stats': 'Statistiques de la plateforme',
        'stats.total_cv': 'Total CV',
        'stats.active_seekers': 'Chercheurs actifs',
        'stats.new_this_week': 'Nouveau cette semaine',
        'stats.total_views': 'Vues totales',
        'stats.matches': 'Correspondances réussies',
        'sidebar.no_job_finders': 'Pas encore d\'embauches.',
        'sidebar.employers': 'Employeurs',
        'sidebar.most_viewed': 'CV les plus consultés',
        'sidebar.no_data': 'Pas encore de données.',
        'sidebar.no_featured': 'Pas encore d\'éléments en vedette.',
        'feed.list_title': 'Liste Kartvizid',
        'feed.sort': 'TRIER',
        'feed.no_results': 'Aucun résultat trouvé.',
        'feed.reset_filters': 'Réinitialiser les filtres',
        'feed.prev': 'Précédent',
        'feed.next': 'Suivant',
        'feed.page': 'Page',
        'mobile.cancel': 'Annuler',
        // Filters
        'filters.categories': 'Toutes Catégories',
        'filters.city': 'Choisir Ville',
        'filters.experience': 'Niveau d\'Expérience',
        'filters.advanced': 'Filtres Avancés',
        'filters.reset': 'Réinitialiser',
        'filters.show_more': 'Montrer Plus',
        // Footer (French) - Simplified for brevity
        'footer.brand_desc': 'Plateforme numérique de CV et de jumelage d\'emploi nouvelle génération en Turquie.',
        'footer.usage': 'Utilisation du site',
        'footer.copyright': '© 2026 Kartvizid. Tous droits réservés.',
        'card.view': 'VOIR',
        'card.years_exp': 'Ans d\'Exp',
        'form.cv_create_title': 'Créer votre CV numérique',
        'form.basic_info_clean': 'INFORMATIONS DE BASE',
        'form.work_pref_clean': 'PRÉFÉRENCES DE TRAVAIL',
        'form.exp_skills_clean': 'ÉDUCATION & COMPÉTENCES',
        'form.education_skills': 'ÉDUCATION & COMPÉTENCES',
        'form.personal_clean': 'DÉTAILS PERSONNELS',
        'form.about_clean': 'À PROPOS / RÉSUMÉ',
        'form.save': 'Enregistrer',
        'form.cancel': 'Annuler',
        'form.add_new': 'Ajouter nouveau',
        'form.add': 'Ajouter',
        'form.add_experience': 'Ajouter une nouvelle expérience',
        'form.currently_working': 'Je travaille actuellement ici',
        'form.institution': 'Nom de l\'institution',
        'form.position': 'Poste',
        'form.start_date_label': 'Début',
        'form.end_date_label': 'Fin',
        'form.university': 'Université / École',
        'form.department': 'Département',
        'form.add_education': 'Ajouter une éducation',
        'form.add_language': 'Ajouter une langue',
        'form.cert_name': 'Nom du certificat / cours',
        'form.cert_issuer': 'Émetteur (Optionnel)',
        'form.cert_date': 'Date d\'obtention',
        'form.add_certificate': 'Ajouter un certificat',
        'form.add_reference': 'Ajouter une nouvelle référence',
        'form.add_list': 'Ajouter à la liste',
        'form.save_publish': 'Enregistrer et publier',
        'form.kvkk_text': "J'ai lu et j'accepte le texte de clarification KVKK.",
        'form.no_skills': 'Vous n\'avez pas encore ajouté de compétences.',
        'form.about_placeholder': 'Présentez-vous de manière impressionnante en 1-2 phrases en mentionnant vos expériences et votre expertise...',
        'form.skills_placeholder': 'React, Gestion de projet, SQL, Figma...',
        'form.fullname_example': 'Ex: Jean Dupont',
        'form.profession_example': 'Ex: Développeur React Senior',
        'form.birth_date': 'Date de naissance',
        'form.preferred_city': 'Ville préférée',
        'form.preferred_roles': 'Domaines préférés',
        'form.roles_placeholder': 'Ajoutez un rôle et appuyez sur Entrée...',
        'form.currently_working_short': 'En cours',
        'form.add_internship': 'Ajouter un stage',
        'form.internships': 'EXPÉRIENCES DE STAGE',
        'form.contact_hint_text': 'Vos coordonnées n\'apparaîtront sur votre profil que si vous cochez la case circulaire située à côté.',
        'common.year': 'An',
        'common.month': 'Mois',
        'success.job_found_title': 'FÉLICITATIONS !',
        'success.job_found_msg': 'Nous vous souhaitons beaucoup de succès dans votre nouveau poste ! En tant que famille Kartvizid, nous avons été heureux de vous accompagner dans votre parcours professionnel.',
        'success.close_btn': 'MERCI',
        'success.card_footer': 'CARTE DE FÉLICITATIONS KARTVİZİD',
        'form.education_info_subtitle': 'Ajoutez votre parcours académique',
        'form.internships_subtitle': 'Ajoutez vos expériences de stage',
        'form.contact_info_subtitle': 'Gérez vos préférences de contact',
        'form.work_history_clean': 'EXPÉRIENCE PROFESSIONNELLE',
        'form.internships_clean': 'STAGES',
        'form.education_info_clean': 'INFORMATIONS SUR L\'ÉDUCATION',
        'form.contact_info_clean': 'INFORMATIONS DE CONTACT',
        'form.fullname': 'Nom Complet',
        'form.profession': 'Profession',
        'form.city': 'Ville',
        'form.experience': 'Expérience',
        'company.create_title': 'Créer Profil Employeur',
        'menu.home': 'Accueil',
        'menu.search': 'Chercher',
        'menu.create': 'Créer',
        'menu.notifications': 'Notifications',
        'menu.profile': 'Profil',
        'profile.cv_title': 'Profil Kartvizid Numérique',
        'profile.about': '6. À PROPOS',
        'profile.references': '7. RÉFÉRENCES',
        'notif.title': 'Toutes les Notifications',

        // Common & Values
        'common.none': 'Aucun',
        'common.no_problem': 'Pas de problème',
        'common.immediately': 'Immédiatement',
        'common.done': 'Fait',
        'common.ongoing': 'En cours',
        'errors.no_about': 'Aucune introduction.',
        'errors.no_exp': 'Aucune expérience professionnelle ajoutée.',
        'common.years_experience': 'ans d\'expérience',
        'errors.ref_name_required': 'Vous devez saisir le nom et le titre pour ajouter une référence.',
        'errors.photo_upload_failed': 'Erreur lors du téléchargement de la photo',
        'errors.kvkk_required': 'Veuillez lire et approuver le texte de la KVKK.',
        'errors.photo_about_required': 'Il est très important de remplir les sections Photo et À propos de moi afin que les employeurs puissent vous remarquer et que vous puissiez obtenir des commentaires positifs. Veuillez remplir ces champs et réessayer pour une meilleure impression.',
        'common.info_msg': 'Message d\'information',
        'common.missing_info': 'Informations manquantes',
        'common.please_note': 'Veuillez noter :',
        'common.please_fill': 'Veuillez remplir les champs suivants :',
        'common.ok_fill': 'D\'accord, je vais remplir',
        'errors.no_ref': 'Aucune référence.',
        'errors.no_contact': 'Aucun contact.',

        // Mappings
        'emp.full_time': 'Temps Plein',
        'emp.part_time': 'Temps Partiel',
        'emp.project': 'Projet',
        'work.office': 'Bureau',
        'work.remote': 'Télétravail',
        'work.hybrid': 'Hybride',
        'military.done': 'Fait',
        'military.exempt': 'Exempté',
        'military.postponed': 'Reporté',
        'marital.single': 'Célibataire',
        'marital.married': 'Marié',
        'grad.graduated': 'Diplômé',
        'grad.student': 'Étudiant',
        'lang.english': 'Anglais',
        'lang.german': 'Allemand',
        'lang.french': 'Français',
        'lang.spanish': 'Espagnol',
        'lang.turkish': 'Turc',
        'lang.russian': 'Russe',
        'lang.arabic': 'Arabe',
        'level.beginner': 'Débutant',
        'level.intermediate': 'Intermédiaire',
        'level.advanced': 'Avancé',
        'level.native': 'Langue Maternelle',
        'travel.yes': 'Peut Voyager',
        'travel.no': 'Ne Peut Pas Voyager',
        'travel.no_barrier': 'Pas d\'Obstacle au Voyage',
        'sort.default': 'Défaut',
        'sort.newest': 'Plus Récents',
        'sort.oldest': 'Plus Anciens',
        'promo.premium_title': 'Privilège Premium',
        'promo.premium_desc': 'Démarquez-vous. Supprimez les limites de vitesse dans votre carrière.',
        'promo.employer_title': 'Talent Ciblé',
        'promo.employer_desc': 'Ne perdez pas de temps avec des annonces. Trouvez directement le professionnel que vous cherchez.',
        'promo.seeker_title': 'Laissez les emplois vous trouver',
        'promo.seeker_desc': 'Ne cherchez pas, laissez-les vous découvrir. Laissez votre profil travailler pour vous.',
        'promo.tips_title': 'Conseils de Pro',
        'promo.tips_desc': 'Découvrez les conseils d\'experts pour une première impression parfaite.',
        'account.title': 'Mon Compte',
        'account.settings': 'Paramètres',
        'account.appearance': 'Apparence',
        'account.dark': 'Sombre',
        'account.light': 'Clair',
        'account.sign_out': 'Se Déconnecter',

        'account.promo_text': 'CRÉEZ VOTRE CARTE DE VISITE NUMÉRIQUE ET COMMENCEZ À ÊTRE DÉCOUVERT PAR LES EMPLOYEURS IMMÉDIATEMENT !',
        'settings.header_title': 'Paramètres du Compte',
        'settings.header_subtitle': 'Gérez vos préférences de profil et de sécurité',
        'settings.account_summary': 'Résumé du Compte',
        'settings.email_label': 'E-mail',
        'settings.member_since': 'Membre depuis',
        'settings.user_id': 'ID Utilisateur',
        'settings.delete_account': 'Supprimer le Compte',
        'settings.delete_desc_emp': 'Votre profil employeur et toutes les données seront définitivement supprimés.',
        'settings.delete_desc_seek': 'Votre CV, vos candidatures et votre profil seront définitivement supprimés.',
        'settings.delete_warning': 'Attention : Cette action est irréversible. Vous perdrez l\'accès à toutes vos données après la suppression.',
        'settings.delete_btn': 'Supprimer le Compte',
        'settings.delete_confirm_title': 'Êtes-vous sûr de vouloir supprimer votre compte ?',
        'settings.delete_confirm_desc_emp': 'Cette action est irréversible. Votre profil employeur et toutes les données seront définitivement supprimés.',
        'settings.delete_confirm_desc_seek': 'Cette action est irréversible. Votre CV, votre profil et toutes les données seront définitivement supprimés.',
        'settings.delete_confirm_yes': 'Oui, Supprimer Mon Compte',
        'settings.change_email': 'Changer l\'E-mail',
        'settings.new_email': 'Nouvelle adresse e-mail',
        'settings.update': 'Mettre à jour',
        'settings.change_password': 'Changer le Mot de Passe',
        'settings.new_password': 'Nouveau mot de passe',
        'settings.new_password_confirm': 'Nouveau mot de passe (répéter)',
        'settings.update_password': 'Mettre à jour le Mot de Passe',
        'settings.notif_email_title': 'Notifications par E-mail',
        'settings.notif_email_desc': 'Recevez des e-mails sur les mises à jour et activités importantes.',
        'settings.notif_marketing_title': 'Messages Marketing',
        'settings.notif_marketing_desc': 'Recevez des informations sur les nouvelles fonctionnalités et campagnes.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Stagiaire',
        'edu.high_school': 'Lycée',
        'edu.associate': 'Diplôme Associé',
        'edu.bachelor': 'Licence',
        'edu.master': 'Master',
        'edu.doctorate': 'Doctorat',
        'grad.dropped_out': 'Abandonné',
        'notice.immediately': 'Immédiatement',
        'notice.2_weeks': '2 Semaines',
        'notice.1_month': '1 Mois',
        'notice.2_months_plus': '2 Mois+',
        'disability.no': 'Non',

        'travel.cannot_travel': 'Ne peut pas voyager',
        'filter.apply': 'Appliquer les Filtres',
        'filter.search_prof_placeholder': 'Rechercher un poste (ex: Logiciel, Serveur...)',
        'filter.search_city_placeholder': 'Rechercher une ville (ex: Istanbul, Antalya...)',
        'filter.salary_title': 'ATTENTE SALARIALE (₺)',
        'filter.salary_min': 'Min',
        'filter.salary_max': 'Max',
        'filter.search_placeholder_dropdown': 'Commencer la recherche...',
        'filter.no_results_dropdown': 'Aucun résultat trouvé...',
        'filter.all_reset': 'Tout (Réinitialiser)',
        'filter.subtitle': 'Listez en détail les résultats qui correspondent le mieux à vos critères',
        'filter.profession_label': 'POSTE / PROFESSION',
        'filter.location_label': 'LIEU / VILLE',
        'filter.work_model_label': 'Modèle de Travail',
        'filter.emp_type_label': 'Type d\'Emploi',
        'filter.edu_level_label': 'Niveau d\'Éducation',
        'filter.grad_status_label': 'Statut de Diplôme',
        'filter.exp_level_label': 'Niveau d\'Expérience',
        'filter.lang_label': 'Langue Étrangère',
        'filter.lang_level_label': 'Niveau de Langue',
        'filter.travel_status_label': 'Statut de Voyage',
        'filter.marital_status_label': 'État Civil',
        'filter.disability_status_label': 'Statut de Handicap',
        'filter.driver_license_label': 'Permis de Conduire',
        'filter.military_status_label': 'Service Militaire',
        'filter.skills_label': 'Compétences Clés',
        'auth.signin_title': 'Bon retour',
        'common.processing': 'Traitement...',
        'auth.selected_type': 'Type de compte sélectionné',
        'auth.signin_desc': 'Entrez vos identifiants pour accéder à votre compte.',
        'auth.signup_title': 'Choisir le type de compte',
        'auth.signup_desc': 'Choisissez le type de compte qui vous convient et rejoignez-nous.',
        'auth.forgot_password': 'Mot de passe oublié',
        'auth.email_label': 'E-mail',
        'auth.password_label': 'Mot de passe',
        'auth.signin_btn': 'Se connecter',
        'auth.signup_btn': "S'inscrire",
        'auth.no_account': "Vous n'avez pas de compte ?",
        'auth.have_account': 'Vous avez déjà un compte ?',
        'auth.signup_now': "S'inscrire maintenant",
        'auth.job_seeker_title': 'Je cherche un emploi',
        'auth.employer_title': 'Je cherche des employés',
        'auth.job_seeker_desc': 'Saisissez les opportunités de carrière',
        'auth.employer_desc': 'Trouvez les meilleurs du secteur',
        'auth.success_signup': 'Inscription réussie !',
        'auth.success_signup_desc': 'Veuillez vérifier votre adresse e-mail. Consultez votre boîte de réception pour activer votre compte.',
    },
    es: {
        'settings.general': 'General',
        'settings.language': 'Selección de idioma',
        'settings.language_desc': 'Cambiar el idioma de visualización de la aplicación.',
        'settings.save': 'Guardar',
        'settings.cancel': 'Cancelar',
        'settings.account': 'Cuenta',
        'settings.security': 'Seguridad',
        'settings.notifications': 'Notificaciones',
        'nav.search_placeholder': 'Buscar profesión, nombre o ciudad...',
        'nav.employer_profile': 'Perfil de empleador',
        'nav.create_cv': 'Crear CV',
        'nav.fix_cv': 'Editar CV',
        'nav.employer': 'Empleador',
        'nav.job_seeker': 'Buscador de empleo',
        'sidebar.job_finders': 'Contratado en Kartvizid',
        'sidebar.popular_professions': 'Profesiones populares',
        'sidebar.featured_cities': 'Ciudades destacadas',
        'sidebar.platform_stats': 'Estadísticas de la plataforma',
        'stats.total_cv': 'Total CVs',
        'stats.active_seekers': 'Buscadores activos',
        'stats.new_this_week': 'Nuevo esta semana',
        'stats.total_views': 'Vistas totales',
        'stats.matches': 'Coincidencias exitosas',
        'sidebar.no_job_finders': 'Aún no hay contrataciones.',
        'sidebar.employers': 'Empleadores',
        'sidebar.most_viewed': 'CVs más vistos',
        'sidebar.no_data': 'Aún no hay datos.',
        'sidebar.no_featured': 'Aún no hay elementos destacados.',
        'feed.list_title': 'Lista Kartvizid',
        'feed.sort': 'ORDENAR',
        'feed.no_results': 'No se encontraron resultados.',
        'feed.reset_filters': 'Restablecer filtros',
        'feed.prev': 'Anterior',
        'feed.next': 'Siguiente',
        'feed.page': 'Página',
        'mobile.cancel': 'Cancelar',
        // Filters
        'filters.categories': 'Todas Categorías',
        'filters.city': 'Sel. Ciudad',
        'filters.experience': 'Nivel de Exp.',
        'filters.advanced': 'Filtros Avanzados',
        'filters.reset': 'Reiniciar',
        'filters.show_more': 'Ver Más',
        // Footer (Spanish) - Simplified
        'footer.brand_desc': 'Plataforma de CV digital y emparejamiento laboral de nueva generación en Turquía.',
        'footer.usage': 'Uso del sitio',
        'footer.copyright': '© 2026 Kartvizid. Todos los derechos reservados.',
        'card.view': 'VER',
        'card.years_exp': 'Años Exp',
        'form.cv_create_title': 'Crear su CV digital',
        'form.basic_info_clean': 'INFORMACIÓN BÁSICA',
        'form.work_pref_clean': 'PREFERENCIAS LABORALES',
        'form.exp_skills_clean': 'EDUCACIÓN Y HABILIDADES',
        'form.education_skills': 'EDUCACIÓN Y HABILIDADES',
        'form.personal_clean': 'DETALLES PERSONALES',
        'form.about_clean': 'ACERCA DE MÍ / RESUMEN',
        'form.save': 'Guardar',
        'form.cancel': 'Cancelar',
        'form.add_new': 'Agregar nuevo',
        'form.add': 'Agregar',
        'form.add_experience': 'Agregar nueva experiencia',
        'form.currently_working': 'Trabajo actualmente aquí',
        'form.institution': 'Nombre de la institución',
        'form.position': 'Puesto',
        'form.start_date_label': 'Inicio',
        'form.end_date_label': 'Fin',
        'form.university': 'Universidad / Escuela',
        'form.department': 'Departamento',
        'form.add_education': 'Agregar educación',
        'form.add_language': 'Agregar idioma',
        'form.cert_name': 'Nombre del certificado / curso',
        'form.cert_issuer': 'Emisor (Opcional)',
        'form.cert_date': 'Fecha de obtención',
        'form.add_certificate': 'Agregar certificado',
        'form.add_reference': 'Agregar nueva referencia',
        'form.add_list': 'Agregar a la lista',
        'form.save_publish': 'Guardar y publicar',
        'form.kvkk_text': 'He leído y acepto el Texto de Aclaración de KVKK.',
        'form.no_skills': 'Aún no has añadido habilidades.',
        'form.about_placeholder': 'Preséntate de forma impresionante en 1 ó 2 frases mencionando tus experiencias y conocimientos...',
        'form.skills_placeholder': 'React, Gestión de proyectos, SQL, Figma...',
        'form.fullname_example': 'Ej: Juan Pérez',
        'form.profession_example': 'Ej: Desarrollador React Senior',
        'form.birth_date': 'Fecha de nacimiento',
        'form.preferred_city': 'Ciudad preferida',
        'form.preferred_roles': 'Áreas preferidas',
        'form.roles_placeholder': 'Añada un rol y pulse Intro...',
        'form.currently_working_short': 'En curso',
        'form.add_internship': 'Agregar pasantía',
        'form.internships': 'EXPERIENCIAS DE PASANTÍA',
        'form.contact_hint_text': 'Sus datos de contacto no aparecerán en su perfil a menos que marque la casilla circular situada junto a ellos.',
        'common.year': 'Año',
        'common.month': 'Mes',
        'success.job_found_title': '¡FELICITACIONES!',
        'success.job_found_msg': '¡Le deseamos mucho éxito en su nuevo trabajo! Como familia de Kartvizid, nos ha encantado acompañarte en tu trayectoria profesional.',
        'success.close_btn': 'GRACIAS',
        'success.card_footer': 'TARJETA DE FELICITACIÓN KARTVİZİD',
        'form.education_info_subtitle': 'Añada su formación académica',
        'form.internships_subtitle': 'Añada sus experiencias de pasantía',
        'form.contact_info_subtitle': 'Gestione sus preferencias de contacto',
        'form.work_history_clean': 'EXPERIENCIA LABORAL',
        'form.internships_clean': 'PASANTÍAS',
        'form.education_info_clean': 'INFORMACIÓN DE EDUCACIÓN',
        'form.contact_info_clean': 'INFORMACIÓN DE CONTACTO',
        'form.fullname': 'Nombre Completo',
        'form.profession': 'Profesión',
        'form.city': 'Ciudad',
        'form.experience': 'Experiencia',
        'company.create_title': 'Crear Perfil Empleador',
        'menu.home': 'Inicio',
        'menu.search': 'Buscar',
        'menu.create': 'Crear',
        'menu.notifications': 'Notificaciones',
        'menu.profile': 'Perfil',
        'profile.cv_title': 'Perfil Kartvizid Digital',
        'profile.about': '6. ACERCA DE MÍ',
        'profile.references': '7. REFERENCIAS',
        'notif.title': 'Todas las Notificaciones',

        // Common & Values
        'common.none': 'Ninguno',
        'common.no_problem': 'Sin problemas',
        'common.immediately': 'Inmediatamente',
        'common.done': 'Hecho',
        'common.ongoing': 'En curso',
        'errors.no_about': 'Sin introducción.',
        'errors.no_exp': 'Sin experiencia.',
        'errors.no_ref': 'Sin referencias.',
        'errors.no_contact': 'Sin contacto.',

        // Mappings
        'emp.full_time': 'Tiempo Completo',
        'emp.part_time': 'Medio Tiempo',
        'emp.project': 'Proyecto',
        'work.office': 'Oficina',
        'work.remote': 'Remoto',
        'work.hybrid': 'Híbrido',
        'military.done': 'Hecho',
        'military.exempt': 'Exento',
        'military.postponed': 'Pospuesto',
        'marital.single': 'Soltero',
        'marital.married': 'Casado',
        'grad.graduated': 'Graduado',
        'grad.student': 'Estudiante',
        'lang.english': 'Inglés',
        'lang.german': 'Alemán',
        'lang.french': 'Francés',
        'lang.spanish': 'Español',
        'lang.turkish': 'Turco',
        'lang.russian': 'Ruso',
        'lang.arabic': 'Árabe',
        'level.beginner': 'Principiante',
        'level.intermediate': 'Intermedio',
        'level.advanced': 'Avanzado',
        'level.native': 'Nativo',
        'travel.yes': 'Puede Viajar',
        'travel.no': 'No Puede Viajar',
        'travel.no_barrier': 'Sin Barreras de Viaje',
        'sort.default': 'Por Defecto',
        'sort.newest': 'Más Recientes',
        'sort.oldest': 'Más Antiguos',
        'promo.premium_title': 'Privilegio Premium',
        'promo.premium_desc': 'Destaca. Elimina los límites de velocidad en tu carrera.',
        'promo.employer_title': 'Talento Exacto',
        'promo.employer_desc': 'No pierdas tiempo con anuncios. Encuentra directamente al profesional que buscas.',
        'promo.seeker_title': 'Deja que te encuentren',
        'promo.seeker_desc': 'No busques, deja que te descubran. Deja que tu perfil trabaje por ti.',
        'promo.tips_title': 'Consejos Profesionales',
        'promo.tips_desc': 'Descubre consejos de expertos para una primera impresión perfecta.',
        'account.title': 'Mi Cuenta',
        'account.settings': 'Configuración',
        'account.appearance': 'Apariencia',
        'account.dark': 'Oscuro',
        'account.light': 'Claro',
        'account.sign_out': 'Cerrar Sesión',

        'account.promo_text': '¡CREA TU TARJETA DE VISITA DIGITAL Y COMIENZA A SER DESCUBIERTO POR LOS EMPLEADORES INMEDIATAMENTE!',
        'settings.header_title': 'Configuración de la Cuenta',
        'settings.header_subtitle': 'Gestiona tus preferencias de perfil y seguridad',
        'settings.account_summary': 'Resumen de la Cuenta',
        'settings.email_label': 'Correo electrónico',
        'settings.member_since': 'Miembro desde',
        'settings.user_id': 'ID de Usuario',
        'settings.delete_account': 'Eliminar Cuenta',
        'settings.delete_desc_emp': 'Tu perfil de empleador y todos los datos se eliminarán permanentemente.',
        'settings.delete_desc_seek': 'Tu CV, solicitudes y perfil se eliminarán permanentemente.',
        'settings.delete_warning': 'Advertencia: Esta acción no se puede deshacer. Perderás el acceso a todos tus datos después de la eliminación.',
        'settings.delete_btn': 'Eliminar Cuenta',
        'settings.delete_confirm_title': '¿Estás seguro de que deseas eliminar tu cuenta?',
        'settings.delete_confirm_desc_emp': 'Esta acción no se puede deshacer. Tu perfil de empleador y todos los datos se eliminarán permanentemente.',
        'settings.delete_confirm_desc_seek': 'Esta acción no se puede deshacer. Tu CV, perfil y todos los datos se eliminarán permanentemente.',
        'settings.delete_confirm_yes': 'Sí, Eliminar Mi Cuenta',
        'settings.change_email': 'Cambiar Correo',
        'settings.new_email': 'Nueva dirección de correo',
        'settings.update': 'Actualizar',
        'settings.change_password': 'Cambiar Contraseña',
        'settings.new_password': 'Nueva contraseña',
        'settings.new_password_confirm': 'Nueva contraseña (repetir)',
        'settings.update_password': 'Actualizar Contraseña',
        'settings.notif_email_title': 'Notificaciones por Correo',
        'settings.notif_email_desc': 'Recibe correos sobre actualizaciones y actividades importantes.',
        'settings.notif_marketing_title': 'Mensajes de Marketing',
        'settings.notif_marketing_desc': 'Recibe información sobre nuevas funciones y campañas.',
        // Filter Options
        'emp.freelance': 'Freelance',
        'emp.intern': 'Pasante',
        'edu.high_school': 'Bachillerato',
        'edu.associate': 'Grado Asociado',
        'edu.bachelor': 'Licenciatura',
        'edu.master': 'Maestría',
        'edu.doctorate': 'Doctorado',
        'grad.dropped_out': 'Abandonado',
        'notice.immediately': 'Inmediatamente',
        'notice.2_weeks': '2 Semanas',
        'notice.1_month': '1 Mes',
        'notice.2_months_plus': '2 Meses+',
        'disability.no': 'No',

        'travel.cannot_travel': 'No Puede Viajar',
        'filter.apply': 'Aplicar Filtros',
        'filter.search_prof_placeholder': 'Buscar Posición (ej: Software, Camarero...)',
        'filter.search_city_placeholder': 'Buscar Ciudad (ej: Estambul, Antalya...)',
        'filter.salary_title': 'EXPECTATIVA SALARIAL (₺)',
        'filter.salary_min': 'Mín',
        'filter.salary_max': 'Máx',
        'filter.search_placeholder_dropdown': 'Empezar a buscar...',
        'filter.no_results_dropdown': 'No se encontraron resultados...',
        'filter.all_reset': 'Todo (Reiniciar)',
        'filter.subtitle': 'Lista en detalle los resultados que mejor se adapten a tus criterios',
        'filter.profession_label': 'POSICIÓN / PROFESIÓN',
        'filter.location_label': 'UBICACIÓN / CIUDAD',
        'filter.work_model_label': 'Modelo de Trabajo',
        'filter.emp_type_label': 'Tipo de Empleo',
        'filter.edu_level_label': 'Nivel Educativo',
        'filter.grad_status_label': 'Estado de Graduación',
        'filter.exp_level_label': 'Nivel de Experiencia',
        'filter.lang_label': 'Idioma Extranjero',
        'filter.lang_level_label': 'Nivel de Idioma',
        'filter.travel_status_label': 'Estado de Viaje',
        'filter.marital_status_label': 'Estado Civil',
        'filter.disability_status_label': 'Estado de Discapacidad',
        'filter.driver_license_label': 'Licencia de Conducir',
        'filter.military_status_label': 'Estado Militar',
        'filter.skills_label': 'Habilidades Clave',
        'common.processing': 'Procesando...',
        'auth.selected_type': 'Tipo de cuenta seleccionado',
    },
    ar: {
        'settings.general': 'عام',
        'settings.language': 'اختيار اللغة',
        'settings.language_desc': 'تغيير لغة عرض التطبيق.',
        'settings.save': 'حفظ',
        'settings.cancel': 'إلغاء',
        'settings.account': 'حساب',
        'settings.security': 'أمان',
        'settings.notifications': 'إشعارات',
        'nav.search_placeholder': 'بحث عن مهنة، اسم أو مدينة...',
        'nav.employer_profile': 'ملف صاحب العمل',
        'nav.create_cv': 'إنشاء سيرة ذاتية',
        'nav.fix_cv': 'تعديل السيرة الذاتية',
        'nav.employer': 'صاحب عمل',
        'menu.home': 'الرئيسية',
        'menu.search': 'بحث',
        'menu.create': 'إنشاء',
        'menu.notifications': 'إشعارات',
        'menu.profile': 'حسابي',
        'nav.job_seeker': 'باحث عن عمل',
        'sidebar.job_finders': 'تم توظيفهم عبر كارتفيزيد',
        'sidebar.popular_professions': 'المهن الشائعة',
        'sidebar.featured_cities': 'المدن المميزة',
        'sidebar.platform_stats': 'إحصائيات المنصة',
        'stats.total_cv': 'إجمالي السير الذاتية',
        'stats.active_seekers': 'الباحثين النشطين',
        'stats.new_this_week': 'جديد هذا الأسبوع',
        'stats.total_views': 'إجمالي المشاهدات',
        'stats.matches': 'تطابقات ناجحة',
        'sidebar.no_job_finders': 'لا يوجد توظيف بعد.',
        'sidebar.employers': 'أصحاب العمل',
        'sidebar.most_viewed': 'السير الذاتية الأكثر مشاهدة',
        'sidebar.no_data': 'لا يوجد بيانات بعد.',
        'sidebar.no_featured': 'لا يوجد عناصر مميزة بعد.',
        'feed.list_title': 'قائمة كارتفيزيد',
        'feed.sort': 'فرز',
        'feed.no_results': 'لم يتم العثور على نتائج.',
        'feed.reset_filters': 'إعادة ضبط الفلاتر',
        'feed.prev': 'السابق',
        'feed.next': 'التالي',
        'feed.page': 'صفحة',
        'feed.end_title': 'وصلت إلى النهاية',
        'feed.end_desc': 'راجع السير الذاتية مرة أخرى.',
        'menu.job_seekers': 'باحثين عن عمل',
        'menu.kartvizid': 'كارتفيزيد',
        'mobile.cancel': 'إلغاء',
        'filters.categories': 'جميع الفئات',
        'filters.city': 'اختر المدينة',
        'filters.experience': 'مستوى الخبرة',
        'filters.advanced': 'فلاتر متقدمة',
        'filters.reset': 'إعادة ضبط',
        'filters.show_more': 'أظهر المزيد',
        'footer.brand_desc': 'منصة السيرة الذاتية الرقمية ومطابقة الوظائف من الجيل الجديد في تركيا.',
        'footer.usage': 'استخدام الموقع',
        'footer.copyright': '© 2026 كارتفيزيد. جميع الحقوق محفوظة.',
        'card.view': 'عرض',
        'card.years_exp': 'سنوات الخبرة',
        'form.cv_create_title': 'أنشئ سيرتك الذاتية الرقمية',
        'form.cv_create_subtitle': 'املأ جميع التفاصيل ليتم اكتشافك من قبل أصحاب العمل',
        'form.basic_info': '1. معلومات أساسية',
        'form.work_pref': '2. تفضيلات العمل',
        'form.exp_skills': '3. التعليم والمهارات',
        'form.personal': '4. تفاصيل شخصية',
        'form.about': '5. نبذة عني',
        'profile.cv_title': 'ملف كارتفيزيد الرقمي',
        'profile.cv_subtitle': 'جميع التفاصيل المهنية والشخصية للمرشح',
        'profile.contact_request': 'اتصال',
        'notif.title': 'جميع الإشعارات',
        'common.none': 'لا يوجد',
        'common.immediately': 'فورا',
        'common.done': 'تم',
        'common.ongoing': 'مستمر',
        'emp.full_time': 'دوام كامل',
        'emp.part_time': 'دوام جزئي',
        'emp.project': 'مشروع',
        'work.office': 'مكتب',
        'work.remote': 'عن بعد',
        'work.hybrid': 'هجين',
        'lang.english': 'الإنجليزية',
        'lang.turkish': 'التركية',
        'lang.arabic': 'العربية',
        'level.beginner': 'مبتدئ',
        'level.intermediate': 'متوسط',
        'level.advanced': 'متقدم',
        'level.native': 'اللغة الأم',
        'travel.yes': 'يمكنه السفر',
        'travel.no': 'لا يمكنه السفر',
        'account.title': 'حسابي',
        'account.settings': 'إعدادات',
        'account.appearance': 'المظهر',
        'account.dark': 'داكن',
        'account.light': 'فاتح',
        'account.sign_out': 'تسجيل الخروج',
        'account.promo_text': 'أنشئ بطاقة عملك الرقمية وابدأ في اكتشافك من قبل أصحاب العمل فورا!',
        'auth.signin_title': 'مرحباً بعودتك',
        'auth.signin_desc': 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى حسابك.',
        'auth.signup_title': 'اختر نوع الحساب',
        'auth.signup_desc': 'اختر نوع الحساب الذي يناسبك وانضم إلينا.',
        'auth.forgot_password': 'نسيت كلمة السر',
        'auth.email_label': 'البريد الإلكتروني',
        'auth.password_label': 'كلمة السر',
        'auth.signin_btn': 'تسجيل الدخول',
        'auth.signup_btn': 'إنشاء حساب',
        'auth.no_account': 'ليس لديك حساب؟',
        'auth.have_account': 'لديك حساب بالفعل؟',
        'auth.signup_now': 'سجل الآن',
        'auth.job_seeker_title': 'أبحث عن عمل',
        'auth.employer_title': 'أبحث عن موظفين',
        'auth.job_seeker_desc': 'اغتنم الفرص المهنية',
        'auth.employer_desc': 'ابحث عن الأفضل في القطاع',
        'auth.success_signup': 'تم التسجيل بنجاح!',
        'auth.success_signup_desc': 'يرجى تأكيد بريدك الإلكتروني. تفقد صندوق الوارد لتفعيل حسابك.',
    },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    // Try to get from localStorage, default to 'tr'
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('app_language');
        return (saved as Language) || 'tr';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);
        // Optional: Reload implementation if deep i18n requires it, 
        // but for React state based i18n, just updating context is enough.
    };

    const t = (key: string): string => {
        const translation = translations[language]?.[key];
        // Fallback to Turkish if missing
        return translation || translations['tr']?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
